### PR TITLE
Split Balearic Islands

### PR DESCRIPTION
**Pull request by systemcatch**
Finally managed to get this done in qgis! Formentera is grey since it has no generation of it's own but really it should be the same colour as Ibiza.

Let me know what you think.

/cc @blackleg 
ref #1347 

split_balearic

### CODE REVIEW

**Comment by corradio** [comment]
cool! Will take a look asap

**Comment by alixunderplatz** [comment]
@corradio looks good to me, too! :)

**Comment by systemcatch** [comment]
@corradio  :grin: lets merge it! Do you think Formentera will be coloured correctly on the main map?

**Comment by corradio** [comment]
If it has no generation I need to add it to our specific exclusion list, else it will appear as grey. Do you confirm that's the thing we should do?

**Comment by systemcatch** [comment]
Actually it has some solar generation running at the moment.

**Pull request merged**
