### PR TITLE
Update Singapore solar capacity

### PR DESCRIPTION
**Pull request by q--**
According to https://www.ema.gov.sg/solarmap.aspx, solar capacity is now
way higher. Because it's also higher than a check in the parser
(which considered everything over 200MW an error), solar would sometimes
wrongly considered invalid. I now updated the maximum value to 400.

### CODE REVIEW

**Comment by brandongalbraith** [comment]
Consider adding yourself to the contributors list below your changes @q--

**Comment by systemcatch** [comment]
@q-- looks good, add yourself to the contributors then I'll merge in.

**Comment by q--** [comment]
Done

**Comment by jarek** [comment]
For tracking: this cap was initially added in #1134 in early 2018 when the reported capacity was 108 MW, so indeed due for an update.

**Pull request merged**
