### PR TITLE
Separate King Island from Tasmania

### PR DESCRIPTION
**Pull request by systemcatch**
ref #636 
/cc @strassburger 

king_island

### CODE REVIEW

**Comment by alixunderplatz** [comment]
@systemcatch another step forward :) looks good!

**Comment by strassburger** [comment]
Thanks,
sorry that i can not help really getting data

**Comment by brandongalbraith** [comment]
Live data: http://www.kingislandrenewableenergy.com.au/

**Comment by jarek** [comment]
@brandongalbraith please see #636 for discussion of that page and difficulties extracting data from it with a script. If you can help it would be great!

**Pull request merged**
