### PR TITLE
add US capacities

### PR DESCRIPTION
**Pull request by KabelWlan**
I added the generation capacites to the US zones. Got the idea from the issue #2495. 

I used the following source, which I'll add to data_sources.md: https://www.eia.gov/electricity/data/eia860M/

(It shows me in the preview that there are some colones missing in the zones AVRN, BPAT and PSEI. I don't know why because they're there in the normal file.) -> figured it out, it was the commas...

### CODE REVIEW

**Review by FelixDQ — CHANGES_REQUESTED** [review]
Thank you @KabelWlan!

Looks like there is a syntax error somewhere in the zones.json. We should be ready to merge if you can fix the issue :-)

**Comment by KabelWlan** [comment]
Finally found my mistake... I hope it’s fine now.

**Comment by martincollignon** [comment]
@KabelWlan you should probably add yourself as a contributor as well :)

**Review by madsnedergaard — APPROVED** [review]

**Review by FelixDQ — APPROVED** [review]
Awesome!

**Pull request merged**
