### PR TITLE
hardcode imports into US-CA at 325 gco2eq/kwh

### PR DESCRIPTION
**Pull request by jarek**
ref #1497

To change the numbers or the assumptions, edit co2eq_parameters.js on this branch.

Otherwise this should work, I hope. I didn't test it though! Sorry, I don't have capacity right now, hopefully others can.

Mock-up of how I expect it'll work visually:

image

And in the exchange hover it'll say "US-intoCA -> United States of America (California)". That could be changed by updating files in web/locales to provide a string for "US-intoCA", but as it only shows on desktop in the hover it seems low priority.

### CODE REVIEW

**Comment by jarek** [comment]
BTW, back-end question: if I were to change co2eq_parameters.js to return closer to 250 g in December, 400 g in June, and blend in between - would that work as expected? That is: is the export CO2 intensity override saved when the export value is saved, or is it every time the intensity is recomputed (and could e.g. return November's value when archive data for June is requested in November)?

Apart from the (very fair) argument that it would complicate our calculations and make them less transparent for relatively little gain...

**Comment by corradio** [comment]
Changing the area name / import name will require us to do a data migration (cc @maxbellec).
@jarek the changes you make affect the past. So only a single carbon intensity number is used, and that's the one on the `master` branch (even for past data, as we recompute it on the fly).
I think the simplest right now is to keep the exchange named the same, but update the parameters?

**Comment by systemcatch** [comment]
I built your branch @jarek but kept getting this error when running update_state.py, other zones work ok still.
```shell
(EM-env) chris@ThinkPad:~/electricitymap$ PYTHONPATH=. python mockserver/update_state.py US-CA
Finding and executing US-CA production parser US_CA.fetch_production..
{ 'datetime': datetime.datetime(2018, 7, 4, 2, 30, tzinfo=tzfile('/usr/share/zoneinfo/US/Pacific')),
  'production': defaultdict(<class 'float'>,
                            { 'biomass': 559.0,
                              'coal': 10.0,
                              'gas': 6668.0,
                              'geothermal': 1005.0,
                              'hydro': 2589.0,
                              'nuclear': 2261.0,
                              'solar': 0.0,
                              'unknown': 0.0,
                              'wind': 2390.0}),
  'source': 'caiso.com',
  'storage': defaultdict(<class 'float'>, {'battery': 20.0}),
  'zoneKey': 'US-CA'}
{ 'datetime': datetime.datetime(2018, 7, 4, 2, 30, tzinfo=tzfile('/usr/share/zoneinfo/US/Pacific')),
  'netFlow': -7165,
  'sortedZoneKeys': 'US-CA->US-intoCA',
  'source': 'caiso.com'}
{ 'datetime': datetime.datetime(2018, 7, 1, 8, 0, tzinfo=tzutc()),
  'netFlow': -48,
  'sortedZoneKeys': 'MX->US-CA',
  'source': 'mysource.com'}
Updating and writing state..
Traceback (most recent call last):
  File "mockserver/update_state.py", line 154, in <module>
    json.dump({'data': obj}, f)
  File "/usr/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 7165 is not JSON serializable
```

**Comment by systemcatch** [comment]
Further digging revealed that the netflow key was type `<class 'numpy.int64'>`, setting it to float makes the json dump work fine.  Not seeing the import having 325g intensity yet though.

ca_export

**Comment by corradio** [comment]
I don't think our mock server supports that right now unfortunately

**Comment by systemcatch** [comment]
Next mockserver milestone then? :grin:

**Comment by jarek** [comment]
> I think the simplest right now is to keep the exchange named the same, but update the parameters?

That's fine by me, except then it might look like we've determined all of US to be 325 g, rather than just the bits that California is importing from.

**Comment by jarek** [comment]
@systemcatch can you push a fix for the `float`/`numpy.int64`? I'm getting seemingly unrelated errors for EIA.py when running update_state

**Comment by jarek** [comment]
@corradio How would you like to proceed? Should I change the import back to `US->US-CA`?

**Comment by jarek** [comment]
CircleCI seems to be frozen, please merge as you see fit if/when it reports

**Pull request merged**
