### PR TITLE
update capacities Spain

### PR DESCRIPTION
**Pull request by KabelWlan**
I updated the capacities with the latest data available. Also I adjusted[ the source.](https://www.ree.es/es/datos/publicaciones/boletines-mensuales/boletin-mensual-junio-2021)

### CODE REVIEW

**Review by madsnedergaard — COMMENTED** [review]
Looks good! 
The numbers are slightly different here, was the source updated or did you find the numbers somewhere else?

Screenshot 2021-07-27 at 08 43 22

**Comment by KabelWlan** [comment]
It is still the same source. I used the "[Boletín mensual. Junio 2021](https://www.ree.es/es/datos/publicaciones/boletines-mensuales/boletin-mensual-junio-2021)" -> Producción -> Data_01.
Also you were looking at the national numbers with all the islands (Canary and Balearic Islands) included. That's probably why I have slightly lower values than you got.

**Review by madsnedergaard — APPROVED** [review]
Thanks for the clarification, I did not consider the islands! 😄

**Comment by lvm1** [comment]
I updated the capacities with the latest data available.
[https://www.ree.es/es/datos/generacion/potencia-instalada](url)
imagen

**Pull request merged**
