### PR TITLE
Separate Flinders Island and Cape Barren Island regions from Tasmania

### PR DESCRIPTION
**Pull request by chuqtas**
This change alters geographic regions only.

- Creates a new region "AUS-TAS-FI" for Flinders Island
- Creates a new region "AUS-TAS-CBI" for Cape Barren Island
   - Note: It does not include providing data for either of these regions.
- Modifies the region "AUS-TAS" to remove the above islands (also a small number of other nearby islands which are not part of the state power grid)

These changes are detailed in part 1 of [issue #2533](https://github.com/tmrowco/electricitymap-contrib/issues/2533)

### CODE REVIEW

**Comment by chuqtas** [comment]
After reviewing the King Island change I've just noticed I hadn't updated /web/locales/en.json or config/zones.json.
I've just added a commit to update en.json, I don't *think* I need to edit zones.json yet because its just geography, no data yet.

**Review by FelixDQ — CHANGES_REQUESTED** [review]
Awesome! Only some small comments and then we should be ready to merge:

1. The system doesn't like geojson FeatureCollections for some reason, so you would need to extract the feature. I.e. Instead of writing:
```json
{
  "type": "FeatureCollection",
  "features": [
    {"type":"Feature", ...}
  ]
}
```
It should just be:
```json
{"type":"Feature", ...}
```



2. And then we need to generate a new `world.json`.  This can be done with the following command (you need docker):
```
docker-compose run --rm web ./topogen.sh
```
See more [here](https://github.com/tmrowco/electricitymap-contrib/tree/master/web)


You can also validate that it looks good by running the map using
```
docker-compose up
```


Let me know if you need help or if I should try to generate the new `world.json`

**Review by chuqtas — COMMENTED** [review]
Remove featureCollection references from geojson files.

**Comment by chuqtas** [comment]
Thanks @FelixDQ!  I have made the necessary changes to the geojson files.  Regarding building the new world.json, I don't have access to a suitable dev environment.  Hopefully you or someone else can help with that?

**Review by FelixDQ — APPROVED** [review]
Thank you @chuqtas! I regenerated world.json :-)

**Comment by chuqtas** [comment]
Thanks for the merge and the earlier assistance with this @FelixDQ  :)

**Pull request merged**
