### PR TITLE
FAQ translation

### PR DESCRIPTION
**Pull request by jld3103**
For #1570.

### CODE REVIEW

**Comment by corradio** [comment]
Hi @jld3103,
Thank you very much for the contribution. Are you able to send a screenshot so we can confirm everything is right? Also, it would be nice if you could sync with upstream changes so we can check that the German translation was left untouched now that we merged the previous PR.

Thanks!

Olivier

**Comment by jld3103** [comment]
electricitymap
You can see that I started translating the FAQ into German.

**Comment by jld3103** [comment]
The FAQ is now completely in German available.

**Comment by corradio** [comment]
Terrific. Thank you. Can you solve the conflicts? Then we'll be good to go

**Comment by alixunderplatz** [comment]
German FAQ-translation has some typos that need to be fixed and a few sentences feel a bit odd or too long. 
However, it's a good start for a proper translation of the missing FAQ! @jld3103 Thanks! 👍  :)

(I won't really have time to look at the translation in detail before Friday.)

**Comment by corradio** [comment]
Looks good to me. @alixunderplatz I'm assigning you to do the last review/merge when you feel it's ready!

**Comment by magol** [comment]
@jld3103 
I like this PR, I want to translate the FAQ to Swedish to. Is it possible to split this PR into two; one only containing the changes in de.json that you can work on until you are satisfied, and one PR containing the rest that can be merged quickly.

**Comment by brunolajoie** [comment]
It's probably simpler to merge this one, and then you can start a new PR from the new master, I guess!

**Comment by jld3103** [comment]
@magol I think @alixunderplatz is working on the translation today as he said.

**Comment by corradio** [comment]
@alixunderplatz anything you wanted to change here or can I merge?

**Comment by jarek** [comment]
I will merge this as there are no objections

**Pull request merged**
