### PR TITLE
Ontario: allow fetching past data, and general updates

### LINKED ISSUE #987: Switch Ontario to using IESO XML data
Use http://reports.ieso.ca/public/IntertieScheduleFlow/PUB_IntertieScheduleFlow_20180108.xml (note that URL changes, using Toronto timezone = UTC-5 / -4) rather than http://live.gridwatch.ca/WebServices/GridWatchWebApp.asmx/GetHomeViewData_v2

Advantages:
* breakdown for every 5 minutes (in browser view, hover/tap on the "flow" values for each hour to see breakdown)
* the "flow" values appear to take into account Lake Erie Loop between Michigan and New York - basically "flow" is the actual electrons on the wire, "exp" is the accounting value

First pointed out by @HansHyde in https://github.com/tmrowco/electricitymap/pull/925#issuecomment-353621704

edit: also use IESO data for generation mix, as it is more official. Live data is at http://www.ieso.ca/en/power-data?chart=supply and historical as XMLO at http://reports.ieso.ca/public/GenOutputCapability/

### PR DESCRIPTION
**Pull request by jarek**
This will finally fix #987

- Updates Ontario capacities
- Allows Ontario fetch_price and fetch_exchange to get data up to 3 months in the past, as fetch_production already could
  - IESO has production and exchange data going back to 2010 (http://www.ieso.ca/Power-Data/Data-Directory) but in a different format (Excel), could be possibly converted and imported offline if you'd like
- Changes timezone returned from "Canada/Eastern" to UTC-5 because IESO says "Eastern Standard Time is used year round."

Comments:
- There is an offset of 1 between hour-stamps of production and price on one hand, and exchanges on the other. I added it when updating fetch_exchange in #1515, but it remains confusing to me, I tried to do my best understanding it, and added some explanatory comments on top of the script - a second set of eyes would be great.
- Production and exchange return datapoints with datetime as [pandas.Timestamp](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html). This should apparently be transparently convertable to Python datetime, is that okay or do you want it explictly returned as datetime?
- I am a little unsure if my specifying constant UTC offset worked, can someone double-check? And I will also check manually once daylight time starts to triple-check.
- I ended up removing the coal=0 preset because that was easier - I don't think it's actually very needed, is it? Capacity is set to 0.

---

Verified outputs are the same from current master and new branch, except for things listed above. Sample outputs below.

**Production**, current master:
```
 {'datetime': datetime.datetime(2019, 2, 20, 3, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')),
  'production': {'biomass': 11.0,
                 'coal': 0,
                 'gas': 1956.0,
                 'hydro': 4577.0,
                 'nuclear': 9084.0,
                 'solar': 0.0,
                 'wind': 582.0},
  'source': 'ieso.ca',
  'storage': {},
  'zoneKey': 'CA-ON'},
...
 {'datetime': datetime.datetime(2019, 2, 20, 14, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')),
  'production': {'biomass': 90.0,
                 'coal': 0,
                 'gas': 1715.0,
                 'hydro': 5121.0,
                 'nuclear': 9083.0,
                 'solar': 151.0,
                 'wind': 2654.0},
  'source': 'ieso.ca',
  'storage': {},
  'zoneKey': 'CA-ON'}
```

New:
```
 {'datetime': Timestamp('2019-02-20 03:00:00-0500', tz='UTC-5'),
  'production': {'biomass': 11.0,
                 'gas': 1956.0,
                 'hydro': 4577.0,
                 'nuclear': 9084.0,
                 'solar': 0.0,
                 'wind': 582.0},
  'source': 'ieso.ca',
  'storage': {},
  'zoneKey': 'CA-ON'},
...
 {'datetime': Timestamp('2019-02-20 14:00:00-0500', tz='UTC-5'),
  'production': {'biomass': 90.0,
                 'gas': 1717.0,
                 'hydro': 5122.0,
                 'nuclear': 9083.0,
                 'solar': 151.0,
                 'wind': 2654.0},
  'source': 'ieso.ca',
  'storage': {},
  'zoneKey': 'CA-ON'}
```

or, new, if I were to use `.to_pydatetime()` on the pandas.Timestamp:

     'datetime': datetime.datetime(2019, 2, 20, 14, 0, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),

**Prices**, current master:
```
 {'currency': 'CAD',
  'datetime': datetime.datetime(2019, 2, 20, 14, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')),
  'price': 28.47,
  'source': 'ieso.ca',
  'zoneKey': 'CA-ON'},
```

New:
```
{'currency': 'CAD',
  'datetime': datetime.datetime(2019, 2, 20, 14, 0, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
  'price': 28.47,
  'source': 'ieso.ca',
  'zoneKey': 'CA-ON'},
```

**Exchanges**, current master:
```
 {'datetime': datetime.datetime(2019, 2, 20, 14, 40, tzinfo=<DstTzInfo 'Canada/Eastern' LMT-1 day, 18:42:00 STD>),
  'netFlow': -1214.8000000000002,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
 {'datetime': datetime.datetime(2019, 2, 20, 14, 45, tzinfo=<DstTzInfo 'Canada/Eastern' LMT-1 day, 18:42:00 STD>),
  'netFlow': -1217.2000000000003,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
 {'datetime': datetime.datetime(2019, 2, 20, 14, 50, tzinfo=<DstTzInfo 'Canada/Eastern' LMT-1 day, 18:42:00 STD>),
  'netFlow': -1222.9,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
```

New:
```
 {'datetime': Timestamp('2019-02-20 14:40:00-0500', tz='UTC-5'),
  'netFlow': -1214.8000000000002,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
 {'datetime': Timestamp('2019-02-20 14:45:00-0500', tz='UTC-5'),
  'netFlow': -1217.2000000000003,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
 {'datetime': Timestamp('2019-02-20 14:50:00-0500', tz='UTC-5'),
  'netFlow': -1222.9,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
```

or sample with `.to_pydatetime()`:

```
 {'datetime': datetime.datetime(2019, 2, 20, 14, 45, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
  'netFlow': -1217.2000000000003,
  'sortedZoneKeys': 'CA-ON->CA-QC',
  'source': 'ieso.ca'},
```

### CODE REVIEW

**Comment by systemcatch** [comment]
Hey @jarek I just took a quick pass over and ran the parser on my laptop, everything looks to be working ok.

On your comments; the UTC offset seems fine, I would convert the Timestamp into a datetime in the parser to avoid having to do it in the backend, and if we leave out coal does it result a in question mark on the generation bar chart?

**Comment by jarek** [comment]
Sorry, I'll try to get the change to python datetime in soon and then check again

**Comment by jarek** [comment]
> if we leave out coal does it result a in question mark on the generation bar chart?

I'm not sure. I updated the zone capacity to 0, maybe that'll help.

fetch_production now returns:

	 ...
	 {'datetime': datetime.datetime(2019, 3, 1, 19, 0, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
	  'production': {'biomass': 91.0,
		         'gas': 4038.0,
		         'hydro': 5482.0,
		         'nuclear': 9097.0,
		         'solar': 0.0,
		         'wind': 144.0},
	  'source': 'ieso.ca',
	  'storage': {},
	  'zoneKey': 'CA-ON'},
	 {'datetime': datetime.datetime(2019, 3, 1, 20, 0, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
	  'production': {'biomass': 85.0,
		         'gas': 3891.0,
		         'hydro': 5520.0,
		         'nuclear': 9096.0,
		         'solar': 0.0,
		         'wind': 211.0},
	  'source': 'ieso.ca',
	  'storage': {},
	  'zoneKey': 'CA-ON'},
	 {'datetime': datetime.datetime(2019, 3, 1, 21, 0, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
	  'production': {'biomass': 84.0,
		         'gas': 4144.0,
		         'hydro': 4958.0,
		         'nuclear': 9096.0,
		         'solar': 0.0,
		         'wind': 393.0},
	  'source': 'ieso.ca',
	  'storage': {},
	  'zoneKey': 'CA-ON'}]

where the one currently live returned:

	 ...
	 {'datetime': datetime.datetime(2019, 3, 1, 19, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')),
	  'production': {'biomass': 91.0,
		         'coal': 0,
		         'gas': 4038.0,
		         'hydro': 5482.0,
		         'nuclear': 9097.0,
		         'solar': 0.0,
		         'wind': 144.0},
	  'source': 'ieso.ca',
	  'storage': {},
	  'zoneKey': 'CA-ON'},
	 {'datetime': datetime.datetime(2019, 3, 1, 20, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')),
	  'production': {'biomass': 85.0,
		         'coal': 0,
		         'gas': 3891.0,
		         'hydro': 5520.0,
		         'nuclear': 9096.0,
		         'solar': 0.0,
		         'wind': 211.0},
	  'source': 'ieso.ca',
	  'storage': {},
	  'zoneKey': 'CA-ON'}]

Seems like the new datasource also updates sooner? The previous hours match and it also has info for 21:00.

fetch_exchange now returns:

	{'datetime': datetime.datetime(2019, 3, 1, 20, 55, tzinfo=datetime.timezone(datetime.timedelta(-1, 68400), 'UTC-5')),
	  'netFlow': 417.6,
	  'sortedZoneKeys': 'CA-ON->US-NY',
	  'source': 'ieso.ca'}

where the one currently live returned:

	 {'datetime': datetime.datetime(2019, 3, 1, 20, 55, tzinfo=<DstTzInfo 'Canada/Eastern' LMT-1 day, 18:42:00 STD>),
	  'netFlow': 417.6,
	  'sortedZoneKeys': 'CA-ON->US-NY',
	  'source': 'ieso.ca'}

Changing to return constant UTC-5 is intended - reasons discussed above and in code comment.

I will be away all day Saturday but will be around on Sunday.

**Comment by corradio** [comment]
@systemcatch I'll let you merge once you feel like everything has been checked!

**Comment by jarek** [comment]
I'll merge now and watch the change once it deploys

**Pull request merged**
