### PR TITLE
Separate Easter Island from Chile-SEN

### LINKED ISSUE #3019: Separate Easter Island from SEN (Chile)
Easter Island (Rapa Nui) is currently included in the Chilean national electric system (Chile-SEN), while it should be kept outside, as the island has its own network and is not connected to the Chilean mainland.

rapa nui

I'm volunteer to give a try at fixing this one, if you agree that the island has indeed to be separated from SEN.

### PR DESCRIPTION
**Pull request by autipial**
Fixes #3019 .
Creates a new CL-CHP zone for Easter Island/Rapa Nui.
CL-SEN is redefined by removing the coordinates of Insular Chile (Easter Island, Salas y Gómez Island, Desventuradas Islands and Juan Fernández Islands). Insular Chile is part of Valparaíso Region but not included in SEN (no interconnector with the mainland).

### CODE REVIEW

**Review by madsnedergaard — COMMENTED** [review]
Nice, thanks for the great work here! :) 

Two things: 

1. With this change, the island is removed from the map entirely - so we should have a separate `CL-CHP.geojson` file in `/third_party_maps` for it :)
I have found the geojson data for you (I extracted it from `tmp_countries.json`):

<details><summary>geojson file content</summary>

```
{"type":"Feature","properties":{"subid":"CHP"},"geometry":{"type":"MultiPolygon","coordinates":[[[[-109.23159745999993,-27.092461846999925],[-109.2200414699999,-27.105238539999903],[-109.22655188699991,-27.118747653999947],[-109.24356035099993,-27.129164320999905],[-109.27391516799992,-27.13567473799992],[-109.29222571499992,-27.145603122999944],[-109.3042699859999,-27.14771900799991],[-109.32384192599994,-27.14902109199994],[-109.33238684799994,-27.15081145599993],[-109.34146074099993,-27.15398528399993],[-109.35130774599992,-27.15984465899993],[-109.35924231699994,-27.166761976999908],[-109.36778723899994,-27.172621351999908],[-109.37930253799993,-27.17506275799991],[-109.3887426419999,-27.17546965899993],[-109.3958227199999,-27.176853122999944],[-109.41030839799993,-27.181898695999905],[-109.41856848899994,-27.19198984199994],[-109.4292699859999,-27.199395440999922],[-109.44066321499992,-27.201429945999905],[-109.45132402299993,-27.195489190999922],[-109.45372473899994,-27.187758070999905],[-109.45103919199994,-27.179294528999947],[-109.44676673099991,-27.17115650799991],[-109.4234106109999,-27.09929778399993],[-109.41319739499994,-27.084730726999908],[-109.39688066299993,-27.06926848799992],[-109.37962805899991,-27.05950286299992],[-109.36632239499994,-27.06178150799991],[-109.31102454299992,-27.08562590899993],[-109.30134029899995,-27.087823174999926],[-109.27916419199994,-27.097100518999923],[-109.26943925699993,-27.09929778399993],[-109.26134192599994,-27.09734465899993],[-109.25194251199991,-27.09343840899993],[-109.24185136599993,-27.09075286299992],[-109.23159745999993,-27.092461846999925]]],[[[-105.45954342399995,-26.464776299999926],[-105.47093665299991,-26.457696221999925],[-105.46593176999994,-26.45549895599993],[-105.46349036399994,-26.456963799999926],[-105.46190344999991,-26.46062590899993],[-105.45954342399995,-26.464776299999926]]]]},"id":"CHL"}
```
</details>

You should also add the new file to `generate-geometries.js` (see how it's done for other zones)

2. After the above is done, you should run `docker-compose run --rm web ./topogen.sh` to generate an updated version of the `world.json`

**Comment by autipial** [comment]
Thanks for the review!

I've added the updated `world.json` file to the PR. I thought it was build on your side for each new release.

Regarding the new CL-CHP zone, fetching it directly in `tmp_countries.json` using `subid` works on my local environment. I thought it was a better solution than creating a new `CL-CHP.geojson` to reduce the number of third party files. What do you think?

**Comment by madsnedergaard** [comment]
Ah of course, good point. Does it work locally for you now? Is the island on the map (as grey)?

**Comment by autipial** [comment]
Yes, it does.

**Review by FelixDQ — APPROVED** [review]
Thank you @autipial! LGTM 🎉

**Pull request merged**
