### PR TITLE
Update Karnataka Unknown Types

### PR DESCRIPTION
**Pull request by zuron7**
From #1867 
Do tell me if I have to make any changes.

### CODE REVIEW

**Comment by systemcatch** [comment]
Hi @zuron7 thanks for the contribution, codewise this looks fine. I'd just like to have @alixunderplatz  check the CO2 figures.

**Comment by corradio** [comment]
@alixunderplatz there's a `renewableRatio` key that you can use for this purpose. It's in the same configuration file if I'm not mistaken.

**Comment by zuron7** [comment]
So, I just set
fossilFuelRatio to 0.80
and 
renewableRatio to 0.20
?

**Comment by corradio** [comment]
Sorry I was a bit fast to respond. Those two keys represent a fallback when data is not present.
What we're looking for here is to override the fact that `unknown` maps to fossil by default. It shouldn't.
The code currently runs on our backend.
What I suggest is to create an issue to make sure this part of the code is open-sourced and can be configured from the JSON file.
How does that sound?

**Pull request merged**
