### PR TITLE
Smarter NL parser

### PR DESCRIPTION
**Pull request by PaulCornelissen**
Since the ENTSO-E data for the Netherlands is still very much incomplete (#78 #1871), I've tried to make a smarter parser:
* It revives the old energieopwek.nl parser that uses the very up to date estimates for solar and wind made by Martien Visser et. al..
* It combines this with ENTSO-E numbers for nuclear, gas, coal, biomass and unknown.
* It checks whether the sum of all these numbers is at least equal to ENTSO-E consumption minus nett imports.

In my opinion the NL data has these issues:
Only some data is reported. Mainly I think that only data from the main TSO is reported. So anything happening on the DSO grid is missed. That's why wind and solar are structurally very low; because most wind farms almost all solar feed into the DSO grid instead of the TSO grid. Coal and nuclear seem to be fairly accurate because there's 3 resp. 1 and they all feed into the TSO net. A lot of gas generation is also missing because NL has a lot of small CHP's (IIRC 4,5GW) and those feed into the DSO grid (mostly?). Possibly also some smaller gas units do this.
Also the consumption data is only the consumption that flows via the TSO grid. That's why especially when there's a lot of solar generation this number is very low. So we can treat this as a minimum, but actual consumption is higher and sometimes a lot higher. That's why I've chosen to add the difference between total generation + nett imports and this consumption number as "unknown" when it has a positive value. That way we should get closer to the actual amount of generation.

### CODE REVIEW

**Comment by q--** [comment]
If I understand correctly your parser will first have the Energieopwek renewable production "eat" the 'unknown' generation part of the ENTSOE mix before adding "on top of" the mix, right?

If so, how do you account for the fact that a lot (most?) of the solar production is (residential) rooftop solar, which from the TSO perspective mostly results in reduced consumption? Should that still 'eat' into the 'unknown' part? Because the other 'unknown'  generators probably won't all have shut down at that point, (gas-fired CHP, biomass plants etc.)

I'm thinking it might make sense to always add solar 'on top' of the mix instead of having it eat into the unknown part first, if that makes sense.

**Comment by PaulCornelissen** [comment]
@q-- It works slightly different. There's two kinds of unknown production:
* Unknown source production reported by ENTSO-E (let's call that entsoe-unknown)
* Unknown source production that's not reported, but what we can calculate, because all ENTSO-E prodcution, energieopwek.nl solar & wind and net imports combined are less than the consumption reported by ENTSO-E. (Let's call this calculated-unknown)

Entsoe-unknown production is never "eaten" by solar and wind. It's just added on top. It's perfectly possible that the sum of all production and net imports is more than the consumption reported by ENTSO-E, because in the real world the actual production is higher than the ENTSO-E reported consumption. 

Calculated-unknown is "eaten" by solar and wind. I don't think we can assume that no significant (or even the majority) part of solar and wind is actually in that calculated-unknown production, so that's why have to let it "eat" that to stay on the conservative side.

**Comment by q--** [comment]
Lots of renewables across much of Europe yesterday. I took a look at the graph for the Netherlands and noticed very little 'unknown' output, which to me suggests that most of the 'unknown' output would be (gas-fired) cogen (especially on days with much 'unknown' output).

Screenshotted ElectricityMap snipped showing very little 'unknown' output when there are high levels of renewables

**Comment by PaulCornelissen** [comment]
@q-- That's not unlikely. However that mostly matters when we want to calculate a custom CO2 intensity for unknown. That is a good idea, but not part of this PR.

@corradio Who can give some feedback on this or possible approve and merge?

**Comment by corradio** [comment]
I will look at it together with @FelixDQ .
Sorry for the delay - I have been swamped lately! Thanks for looking at it.

**Comment by FelixDQ** [comment]
Hi @PaulCornelissen
I'm very sorry for the delay. Really nice work on this!

Before we merge this I just want to get some insights from ENTSOE to make sure that our assumptions are correct. I have reached out to them and I will update here as soon as I get a response.

We can hopefully get this merged soon :-)

**Comment by PaulCornelissen** [comment]
Hi @FelixDQ,

Good to hear! 

Yes, that around the time that the DK->NL interconnector was added. I believe it was added a bit later officially (IIRC), but maybe that's the date they updated the statistics. So it makes sense to hard-code to zero before that.

**Comment by FelixDQ** [comment]
Awesome! Would you be able to do that in this parser? :-)

**Comment by PaulCornelissen** [comment]
Yes probably, time allowing.

**Comment by FelixDQ** [comment]
Hey @PaulCornelissen, do you think that you have time to do the final change or should I go ahead and finish it up? :-)

**Comment by tth4vb** [comment]
Hey @PaulCornelissen :) Checking to see if you had time to make the final change, otherwise we'll see if we can find time in our dev cycle to finish!

**Comment by PaulCornelissen** [comment]
Sorry, started a new job recently which had me quite preoccupied. I started working on this 3x al ready, but I found another larger bug. I at least pushed the fix for the DK interconnector not working for very historic dates. But that other bug remains. I just had a good look at it: 

@FelixDQ what is the exact expected behavior of the `--target_datetime` option? Because the ENTSOE parser doesn't actually return any values for the specified date, rather it only returns data for 2 days _preceding_ the specified date. I find this "up to, but not including" interpretation not very intuitive tbh, but if that's the expected behavior, then I'll adjust the NL parser. 

(Currently the e-opwek parser gets values for the specified date also and because the ENTSOE parser doesn't return any values for the specified date, the merging of the two sets goes wrong.)

**Comment by tth4vb** [comment]
@PaulCornelissen no worries! @FelixDQ is on vacation but can get back to you next week :)

**Comment by PaulCornelissen** [comment]
@tth4vb With the last commit the parser now only returns datapoints for which both ENTSOE and energieopwek.nl return data. Because of the way the ENTSOE handles the --target_datetime this means the 26hrs (due to timezones) preceding the specified date are returned. 

If that's ok, then I think this can now be merged.

**Comment by FelixDQ** [comment]
This looks good to me.  🎉 

I need to run some tooling and look at the data when merging this. I'll do this next week at the latest.

**Review by FelixDQ — APPROVED** [review]
Let's merge 🎉

Thanks for the great work @PaulCornelissen !

**Comment by mhooi** [comment]
I was wondering wat the reasoning is behind the assumed 700 gCO2eq/kWh carbon intensity for the unknown part of the Netherlands? We know that the majority of the electricity is generated by Gas stations currently so a value around the 490 gCO2eq/kWh would be a better guestimate I think for the Netherlands.

**Comment by PaulCornelissen** [comment]
@mhooi There was non. 700 gCO2eq/kWh is the universal number for unknown.

See also this issue: #738 

You are probably right though. All coal production (there's only 4 plants left) is probably reported as coal in ENTSOE. NL is unlikely to have any significant oil based generation (like the rest of continental Europe), so that means unknown is probably all gas of some kind (CHP, gas turbine and CCGT). You should open a new issue and explain this reasoning a bit further and probably collect some data/sources to back it up and then propose a custom value for unknown.

**Pull request merged**
