### PR TITLE
feat(web-locales, ru): Add a bunch of translations to Russian locale

### PR DESCRIPTION
**Pull request by steppefox**
## Description

Add a couple of Russian translations for new keys. Not all of the keys were added, around 20-30 keys still have to be translated (they are not presented in the changes).

### CODE REVIEW

**Comment by steppefox** [comment]
@lgrigoryeva1 could you please take a brief look to this PR and make sure that I didn't make any mistake? 🙏

**Comment by corradio** [comment]
@lgrigoryeva1 could you take a look? Thanks!

**Comment by lgrigoryeva1** [comment]
Sorry folks, didn't have time to actually fix the translations in the file, but I left the correct versions as comments.

**Comment by steppefox** [comment]
@corradio changes applied

**Pull request merged**
