### PR TITLE
Get IN-PB solar from new source

### PR DESCRIPTION
**Pull request by lorrieq**
Filtering out units with BIOMASS in name and units with `SUSPECT` . Is this strict enough or do we need a specific biomass mapping?

How do we deal with the `datetime` where we read different fuels from different sources? Do we want to return the latest `datetime` across the two webpages? I have not parsed out any timestamps in the solar source yet but we could select the latest updated timestamp from the table if needed.

issue #1647

### CODE REVIEW

**Comment by systemcatch** [comment]
Good stuff, all that's left is to deal with the timestamps in the solar/biomass data. We could compare each one to india_date on https://github.com/tmrowco/electricitymap-contrib/pull/1652/files#diff-7038aab9af0a61c166116ea2b61de64dL37 to see if it's current enough to use?

**Comment by lorrieq** [comment]
Currently implemented to only include values from biomass and solar units updated later than 30 minutes before the datetime of the main parser but this threshold can be changed.

**Comment by systemcatch** [comment]
@lorrieq merge away!

**Comment by corradio** [comment]
Thank guys!

**Pull request merged**
