### PR TITLE
Update Estonian Production Capacities From Renovable Sources

### PR DESCRIPTION
**Pull request by Vaikevimbu**
Updated Estonian production capacities according to The Estonian Renewable Energy Association (EREA) 2019 report. http://www.taastuvenergeetika.ee/wp-content/uploads/2020/10/ETEK_aastaraamat_A4_2019_veeb.pdf It is in Estonian, foreigners can use Google Translate. Wind energy (tuuleenergia) stats are on page 20, sun energy (päikeseenergia) on page 22, hydro on page 26 and other renewable sources (mostly sun energy from mircro-producers) on page 27. ENTSO-E data is similar, but EREA should have the most precise data.

### CODE REVIEW

**Comment by tth4vb** [comment]
@Vaikevimbu thanks for this! Should we be updating hydro as well?

**Comment by Vaikevimbu** [comment]
There is no change in hydro electricity capacity in Estonia for years now, because it is not favoured. Decimal number is 7,3MW, I would round it to 7MW, as it was already.

**Comment by tth4vb** [comment]
ah, that's my bad for trying to read Estonian and choosing the wrong number ;)

**Review by tth4vb — APPROVED** [review]

**Comment by Vaikevimbu** [comment]
Do I have to do something more or when will the changes take effect? At the moment the electricity Map is still showing old capacities for Estonia and I am wondering if something more needs to be done. Thnx.

**Pull request merged**
