### PR TITLE
Update AT capacities

### PR DESCRIPTION
**Pull request by scriptator**
I updated the production capacities for Austria because I noticed that the solar generation sometimes exceeded the stated capacity.

The aggregation of values has been done by using the mapping defined in `parsers.ENTSOE.ENTSOE_PARAMETER_GROUPS`. That is
    
    biomass -> "Biomass" + "Waste"
    coal -> "Fossil Brown coal/Lignite" + "Fossil Hard coal" + "Fossil Oil shale" + "Fossil Peat"
    gas -> "Fossil Coal-derived gas" + "Fossil Gas"
    geothermal -> "Geothermal"
    hydro -> "Hydro Run-of-river and poundage" + "Hydro Water Reservoir"
    nuclear -> "Nuclear"
    oil -> "Fossil Oil"
    solar -> "Solar"
    wind -> "Wind Offshore" + "Wind Onshore"
    unknown -> "Other" + "Marine" + "Other renewable"
    hydro storage -> "Hydro Pumped Storage"

To ease further updates I have written a script which is capable of performing this capacity update to the file `zones.json` automatically, given the corresponding CSV export file from ENTSOE. You can find the script [here](https://github.com/scriptator/electricitymap-contrib/blob/entsoe_capacity_parsing/utils/update_capacities_entsoe.py ). If you consider such a script a useful contribution and would like to have it in this repo, I'll open a separate pull request for that.

### CODE REVIEW

**Comment by corradio** [comment]
Hi @scriptator , thank you for this PR.
The script you have made would indeed be useful. Feel free to include it another PR.
I'll let @alixunderplatz review the PR with the capacities.

**Comment by corradio** [comment]
@alixunderplatz are you able to quickly review here?

**Comment by corradio** [comment]
Seems like capacities have already been updated. Feel free to re-open if you believe they are still wrong

**Comment by scriptator** [comment]
> Seems like capacities have already been updated. Feel free to re-open if you believe they are still wrong

The capacity update only concerned the shut-down of a coal plant, not the other categories. For example, solar production still exceeds the production capacity (regarding to zones.json) almost every day.

Do you mean I should create a new pull request? I do not see a possibilty to reopen this one

**Comment by corradio** [comment]
I have re-opened this PR

**Comment by scriptator** [comment]
> OK - I have re-opened this PR. Are you able to fix the conflicts (config/zones.json)?

Yes, the conflicts are easy to fix. However, I do not think that the changes which were made in #1920 are correct. @peterpoetzi are you sure that there is no coal power plant left? Regarding this [article](https://steiermark.orf.at/v2/news/stories/2984926/) Mellach is still active (until 2020).

**Comment by peterpoetzi** [comment]
@scriptator you are completely right. Kohlekraftwerk Mellach can still produce 225MW electric.

**Comment by scriptator** [comment]
Sry for the delay - now I resolved the conflicts and made the change to the coal category so that it states 225MW.

**Comment by systemcatch** [comment]
Thanks @scriptator!

**Pull request merged**
