### PR TITLE
Fetch near-real-time data for Chile

### PR DESCRIPTION
**Pull request by alixunderplatz**
Hi electricityMappers ⚡️,
we're still lacking real-time data for Chile, but the data for ~~"now - 5 or 6 hours"~~ "now - 11 or 12 hours" is available and looks okay to me.
So instead of using the parser for parsing historical data only, I decided to convert it to fetching the latest near-real-time data when no `target_datetime` is specified.
Hope this is fine for you. The latest available data should fill about ~~18~~ 12 hours of the 24 hour-graph. 

This will make the electricityMap-data for Chile even a bit faster in comparison to what is displayed on https://www.coordinador.cl/operacion/graficos/operacion-programada/programa-diario-de-generacion/

I tried to implement a logger.warning which pops up everytime the data is fetched:
```
logger.warning('The real-time data collected by the parser is incomplete for the latest datapoints/hours,'
                       'so the last 3 datapoints were omitted.'
                       'If desired, please specify a historical date in YYYYMMDD format.')
```
Would it work this way and show up in kibana or is it annoying to have this info popping up every time you run the parser?

Sample output of complete list of available data:
```
fetch_production() ->
The real-time data collected by the parser is incomplete for the latest datapoints/hours,so the last 3 datapoints were omitted.If desired, please specify a historical date in YYYYMMDD format.
[{'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 1, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2414.1515384098, 'geothermal': 25.834, 'unknown': 6564.3751096264, 'solar': 0.0026687444, 'wind': 204.4083653707}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 2, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027856822, 'hydro': 2243.5438822036, 'wind': 176.6534779678, 'geothermal': 25.7813, 'unknown': 6360.7969679764}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 3, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0028353679, 'hydro': 2245.2554789135, 'wind': 172.3544245581, 'geothermal': 25.6717, 'unknown': 6078.5134100645}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 4, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 6057.3376086444, 'geothermal': 25.8276, 'hydro': 2091.5054927194, 'wind': 186.7869839492, 'solar': 0.0027845319}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 5, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'geothermal': 25.825, 'unknown': 6096.3385201596, 'wind': 213.8282168452, 'hydro': 1974.2037413925, 'solar': 0.0027599874}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 6, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027915136, 'wind': 232.1219874819, 'hydro': 2014.0847573257, 'unknown': 6060.1425257895, 'geothermal': 25.9365}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 7, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'geothermal': 26.0773, 'unknown': 6032.7634985623, 'hydro': 2197.8986785445, 'wind': 256.2713570088, 'solar': 0.0699913162}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 8, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2322.8383993793, 'geothermal': 26.2112, 'unknown': 6041.4498418946, 'solar': 28.252949258, 'wind': 283.9730530057}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 9, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 662.4606116514, 'geothermal': 25.8146, 'unknown': 5955.5201833317, 'hydro': 2327.2439429517, 'wind': 235.076153727}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 10, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2287.5873524795, 'wind': 139.7119623114, 'geothermal': 25.5132, 'unknown': 5648.7403888261, 'solar': 1529.4750051566}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 11, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 70.7763403304, 'hydro': 2356.2158799601, 'solar': 1841.8220639883, 'unknown': 5579.3409924801, 'geothermal': 24.957}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 12, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2154.793267532, 'geothermal': 24.5381, 'unknown': 5812.3012854002, 'solar': 2024.4499876128, 'wind': 78.5915045355}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 13, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 2130.7778896802, 'geothermal': 23.8832, 'unknown': 5850.9387681522, 'wind': 186.5588682439, 'hydro': 1930.2491911849}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 14, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 246.8990722971, 'unknown': 5699.2175534474, 'geothermal': 23.8275, 'solar': 2179.2449293823, 'hydro': 1993.5295437764}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 15, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 329.3443679958, 'geothermal': 23.7203, 'unknown': 5689.4732247235, 'solar': 2204.4647859112, 'hydro': 1965.8978529198}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 16, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 1929.4541659315, 'wind': 343.8089038172, 'solar': 2191.6960666459, 'geothermal': 24.2798, 'unknown': 5669.8257060731}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 17, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 348.383883605, 'geothermal': 26.0379, 'unknown': 5671.6448341691, 'solar': 2072.1167117238, 'hydro': 1957.7448147662}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 18, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 1986.095693766, 'wind': 356.214344137, 'solar': 1911.9361865354, 'unknown': 5648.9056960979, 'geothermal': 26.1274}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 19, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 1482.2020014683, 'wind': 340.2370543045, 'hydro': 2256.9721915476, 'geothermal': 26.9463, 'unknown': 5548.7381774737}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 20, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 449.4992080045, 'unknown': 6204.2456846012, 'geothermal': 27.1607, 'hydro': 2598.1745885228, 'wind': 316.4796768651}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 21, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 8.1364815202, 'hydro': 3066.3557979619, 'wind': 232.21336343, 'geothermal': 26.9028, 'unknown': 6428.0635665464}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 22, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.3028237826, 'geothermal': 26.9743, 'unknown': 6721.9160170523, 'wind': 204.525994876, 'hydro': 3175.5926916923}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 23, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 6934.8399208608, 'geothermal': 27.0172, 'wind': 200.7241233876, 'hydro': 2728.860736532, 'solar': 0.102730881}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 0, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027251031, 'geothermal': 26.9042, 'unknown': 6908.1686606782, 'hydro': 2400.1237409267, 'wind': 162.5066410627}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 1, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 2671.4772996997, 'hydro': 1832.2651350909, 'wind': 110.2246795939, 'solar': 0.0027019335}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 2, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027849719, 'unknown': 2436.2027069704, 'hydro': 1777.7501020349, 'wind': 99.1470976441}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 3, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 2253.1579823576, 'hydro': 1718.0744777839, 'wind': 93.226146538, 'solar': 0.0028240316}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 4, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 1587.5530247018, 'unknown': 2250.9786252357, 'solar': 0.0027614238, 'wind': 73.4149336548}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 5, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027409467, 'wind': 46.4253611615, 'hydro': 1582.5155605136, 'unknown': 2250.6108650149}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 6, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0028407963, 'unknown': 2192.4381855781, 'wind': 29.6460267238, 'hydro': 1723.0037507559}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 7, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.001469598, 'hydro': 1688.8334793799, 'wind': 9.2426813355, 'unknown': 1887.2956276137}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 8, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 782.904, 'wind': 9.27, 'hydro': 1471.575, 'solar': 3.046}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 9, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.5, 'hydro': 1.7, 'wind': 0.0, 'unknown': 13.3}, 'storage': {}, 'source': 'coordinador.cl'}]
```

Sample output of the same dataset but without the last ~~3 dicts of the list [:-3]~~
 9 dicts of the list [:-9]
```
fetch_production() ->
The real-time data collected by the parser is incomplete for the latest datapoints/hours,so the last 3 datapoints were omitted.If desired, please specify a historical date in YYYYMMDD format.
[{'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 1, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2414.1515384098, 'geothermal': 25.834, 'unknown': 6564.3751096264, 'solar': 0.0026687444, 'wind': 204.4083653707}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 2, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027856822, 'hydro': 2243.5438822036, 'wind': 176.6534779678, 'geothermal': 25.7813, 'unknown': 6360.7969679764}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 3, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0028353679, 'hydro': 2245.2554789135, 'wind': 172.3544245581, 'geothermal': 25.6717, 'unknown': 6078.5134100645}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 4, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 6057.3376086444, 'geothermal': 25.8276, 'hydro': 2091.5054927194, 'wind': 186.7869839492, 'solar': 0.0027845319}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 5, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'geothermal': 25.825, 'unknown': 6096.3385201596, 'wind': 213.8282168452, 'hydro': 1974.2037413925, 'solar': 0.0027599874}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 6, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027915136, 'wind': 232.1219874819, 'hydro': 2014.0847573257, 'unknown': 6060.1425257895, 'geothermal': 25.9365}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 7, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'geothermal': 26.0773, 'unknown': 6032.7634985623, 'hydro': 2197.8986785445, 'wind': 256.2713570088, 'solar': 0.0699913162}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 8, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2322.8383993793, 'geothermal': 26.2112, 'unknown': 6041.4498418946, 'solar': 28.252949258, 'wind': 283.9730530057}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 9, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 662.4606116514, 'geothermal': 25.8146, 'unknown': 5955.5201833317, 'hydro': 2327.2439429517, 'wind': 235.076153727}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 10, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2287.5873524795, 'wind': 139.7119623114, 'geothermal': 25.5132, 'unknown': 5648.7403888261, 'solar': 1529.4750051566}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 11, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 70.7763403304, 'hydro': 2356.2158799601, 'solar': 1841.8220639883, 'unknown': 5579.3409924801, 'geothermal': 24.957}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 12, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 2154.793267532, 'geothermal': 24.5381, 'unknown': 5812.3012854002, 'solar': 2024.4499876128, 'wind': 78.5915045355}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 13, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 2130.7778896802, 'geothermal': 23.8832, 'unknown': 5850.9387681522, 'wind': 186.5588682439, 'hydro': 1930.2491911849}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 14, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 246.8990722971, 'unknown': 5699.2175534474, 'geothermal': 23.8275, 'solar': 2179.2449293823, 'hydro': 1993.5295437764}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 15, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 329.3443679958, 'geothermal': 23.7203, 'unknown': 5689.4732247235, 'solar': 2204.4647859112, 'hydro': 1965.8978529198}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 16, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 1929.4541659315, 'wind': 343.8089038172, 'solar': 2191.6960666459, 'geothermal': 24.2798, 'unknown': 5669.8257060731}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 17, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'wind': 348.383883605, 'geothermal': 26.0379, 'unknown': 5671.6448341691, 'solar': 2072.1167117238, 'hydro': 1957.7448147662}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 18, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'hydro': 1986.095693766, 'wind': 356.214344137, 'solar': 1911.9361865354, 'unknown': 5648.9056960979, 'geothermal': 26.1274}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 19, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 1482.2020014683, 'wind': 340.2370543045, 'hydro': 2256.9721915476, 'geothermal': 26.9463, 'unknown': 5548.7381774737}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 20, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 449.4992080045, 'unknown': 6204.2456846012, 'geothermal': 27.1607, 'hydro': 2598.1745885228, 'wind': 316.4796768651}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 21, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 8.1364815202, 'hydro': 3066.3557979619, 'wind': 232.21336343, 'geothermal': 26.9028, 'unknown': 6428.0635665464}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 22, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.3028237826, 'geothermal': 26.9743, 'unknown': 6721.9160170523, 'wind': 204.525994876, 'hydro': 3175.5926916923}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 21, 23, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'unknown': 6934.8399208608, 'geothermal': 27.0172, 'wind': 200.7241233876, 'hydro': 2728.860736532, 'solar': 0.102730881}, 'storage': {}, 'source': 'coordinador.cl'}, {'zoneKey': 'CL', 'datetime': datetime.datetime(2020, 2, 22, 0, 0, tzinfo=tzfile('Chile/Continental')), 'production': {'solar': 0.0027251031, 'geothermal': 26.9042, 'unknown': 6908.1686606782, 'hydro': 2400.1237409267, 'wind': 162.5066410627}, 'storage': {}, 'source': 'coordinador.cl'}]
```

### CODE REVIEW

**Comment by alixunderplatz** [comment]
Edit: I just realized I must skipp a few more hours of "bad data"
image

Anyway we'd have like half the data in the 24h graph^^
fixing...

**Comment by robertahunt** [comment]
Also, personally I think the logger warning should be okay. It is easy enough to filter warnings from errors. 

Just to let you know - I haven't gotten a response on access to the official chile api so it looks like this is the best solution for now. Hope they will respond at some point!!

**Comment by AyrtonB** [comment]
Is there any benefit in using the 'https://sipub.coordinador.cl/api/v1/recursos/generacion_programada_tecnologia_horario' stream for planned generation if its important to have more up-to-date info?

**Comment by robertahunt** [comment]
Hey @AyrtonB , It would be great to display more up to date info, but at the moment I don't want to mix actual production values with expected generation. 

We are currently discussing internally how to combine estimations of data, actual data, and data from various parsers, so this might be something that can be solved in the future, when we have some infrastructure in place.

**Pull request merged**
