### PR TITLE
Fixing and Adding GB Exchanges

### LINKED ISSUE #2829: GB (ELEXON parser) exchanges broken
~~Kibana:~~

>~~Expected 19 fields in FUELINST report, got 22
>Traceback (most recent call last):  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 176, in launch_parsers   objs = res.get(timeout)  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get      raise self._value  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker      result = (True, func(*args, **kwds))  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 174, in <lambda>      **parser_kwargs))  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 289, in fetch_production      wind = _fetch_wind(target_datetime)  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 253, in _fetch_wind      report['expected_fields'], len(df.columns)))  
ValueError: Expected 19 fields in FUELINST report, got 22~~
  
***Edit:** Fixed in #2828. Exchanges still broken*

Exchanges with FR, NL and IE are broken too. Exchanges with BE and GB-NIR are still working, but those use ENTSOE and the GB_NIR parser, respectively

>Expected 8 fields in INTERFUELHH report, got 11

>Traceback (most recent call last):  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 176, in launch_parsers      objs = res.get(timeout)  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get      raise self._value  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker      result = (True, func(*args, **kwds))  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 174, in <lambda>      **parser_kwargs))  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 277, in fetch_exchange      logger)  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 130, in parse_exchange     report['expected_fields'], field_count))  
ValueError: Expected 8 fields in INTERFUELHH report, got 11  

Same error for those three exchanges

### LINKED ISSUE #2832: Add North Sea Link (GB<->NO-NO2)
National Grid and Statnett are building an interconnector ([1400MW](https://northsealink.com/)) between Great Britain and [South-West Norway](https://northsealink.com/en/locations/norway/) (should be NO-NO2 based on physical location).

Installation of subsea cables is only [planned](https://northsealink.com/en/the-project/project-timeline/) to be finished in 2021, but apparently the interconnector has already been added to ELEXON and possibly [broken](/tmrowco/electricitymap-contrib/pull/2828) that [parser](/tmrowco/electricitymap-contrib/issues/2829).

So, it seems to be possible to add the exchange to ElectricityMap. I can't find it in ENTSO-E yet though, so if we want to use that one instead of ELEXON we'll have to wait.

### PR DESCRIPTION
**Pull request by ilfrich**
This PR should fix the ELEXON parser's exchanges:

- Fixing the number of columns for the exchanges CSV (causing errors at the moment - should fix #2829)
- Replacing the `GB-NIR->IE` link with `GB->GB-NIR` - `GB-NIR->IE` is covered by the `GB_NIR` parser and ELEXON actually returns `GB->GB-NIR` instead (this was wrong, couldn't find an existing issue for it, but it's using `GB_NIR` parser anyway, so didn't cause issues so far)
- Adding new `GB->NO-NO2` exchange (should fix #2832)
- Adding support for multiple `FR->GB` links (2 more have been added IFA2 and Eleclink)

The 3 new links currently provide either 0 values (FR) or no value (NO, FR).
Not sure how to test the rotation of the new `NO-NO2` exchange, but I think 50 degrees should be about right.

### CODE REVIEW

**Review by q-- — APPROVED** [review]
LGTM. Haven't run the parser because I don't have an ELEXON key though.

**Comment by Gazer75** [comment]
Could you change the NorNed cable capacity to 723MW as well so I do not have to make a pull request just for that?
The actual sent amount is 723 to get 700MW on the receiving end due to losses. 
Search the web for "NorNed 723 MW" and you'll see. Can also be seen at ENTSOE history of transmissions.

**Comment by q--** [comment]
> Could you change the NorNed cable capacity to 723MW as well so I do not have to make a pull request just for that?
> The actual sent amount is 723 to get 700MW on the receiving end due to losses.
> Search the web for "NorNed 723 MW" and you'll see. Can also be seen at ENTSOE history of transmissions.

Hmm, are you sure we should include the transmission losses with the capacity? After all, the amount that actually ends up at the receiving side is less than that.

**Comment by Gazer75** [comment]
It is what is being reported at ENTSOE by Statnett. They also put this at Nord Pool exchange as available capacity for trading.

**Comment by ilfrich** [comment]
According to NordPool the extra 23MW are not usable, so why include them in the capacity if the actual transfer rate cannot be higher than 700MW? 
- https://umm.nordpoolgroup.com/#/messages/c48bba42-bceb-422f-ac1c-3bf45b2f4314/5

Additionally every other source including TenneT (NL), Statnett (NO), ENTSOE and all related Wikipedia pages lists it as 700MW:
- https://eepublicdownloads.entsoe.eu/clean-documents/Publications/SOC/Nordic/Nordic-and-Blatic-HVDC-Disturbance-Statistics-2017.pdf
- https://www.tennet.eu/our-grid/international-connections/norned/
- https://www.statnett.no/en/about-statnett/news-and-press-releases/News-archive-2013/the-norned-cable-back-in-operation-/
- https://en.wikipedia.org/wiki/Statnett and https://en.wikipedia.org/wiki/NorNed

As this seems a bit controversial, for now, I would not include this.

**Comment by ilfrich** [comment]
I see however, that other connectors like `LT->PL` are actually listed with their installed capacity (including the losses)
- https://umm.nordpoolgroup.com/#/messages/bf0bd6f7-ddbc-478d-aebe-e271f49d254f/1
(-500, 500) in exchanges.json

**Comment by ilfrich** [comment]
Gonna rename this, so there's no confusion with inconsistencies in other areas. If the `NL->NO-NO2` link is considered incorrect, I suggest handling this in a separate issue. I've just been fixing/extending the ELEXON parser.

**Comment by Gazer75** [comment]
> According to NordPool the extra 23MW are not usable, so why include them in the capacity if the actual transfer rate cannot be higher than 700MW?

The 23MW has to be generated somewhere and will cause pollution. The numbers on a maxed NorNed listed hourly is 723MW.
So the actual send rate is 723MW resulting in around 700MW at receiving end. Heck I've even seen 731MW at times.

The values are just simplifications. Skagerak 1-4 HVDC has an installed capacity of 1632MW, but it is listed in most places as 1700MW total. Do a google search for "skagerrak hvdc 1700 mw" and you'll see.

https://umm.nordpoolgroup.com/#/messages/8f9738ef-71c5-4bb8-816c-a00290516007/10

I'm fine with making a separate pull request on this.

**Comment by Kongkille** [comment]
I'm fine with either, but perhaps you can make the other PR @Gazer75, so we can take that discussion there? Just so it's not blocking here :)

**Comment by ilfrich** [comment]
Anyone fancy merging this? :)

**Review by Kongkille — APPROVED** [review]

**Pull request merged**
