### PR TITLE
fix(parsers): bolivia now uses json

### PR DESCRIPTION
**Pull request by byronwilliams**
@q-- I've updated the Bolivia parser to use JSON as per your comment in #2882

### CODE REVIEW

**Comment by skovhus** [comment]
@q-- let me know if you have some feedback here, as I see that you already worked a bit on [fixing this issue](https://github.com/q--/electricitymap-contrib/tree/Fix_BO_parser).

**Comment by skovhus** [comment]
@byronwilliams thanks for fixing this.

I tried to validate the parser here by running `test-parser.py BO`. It does fail with a `json.decoder.JSONDecodeError`. I tried inspecting the `resp.text` and see that it contains some odd characters:

```
>>> resp = r.get(url_init.format(formatted_date))
>>> resp.text
'ï»¿{"data":[]}'
```

**Comment by Kongkille** [comment]
@byronwilliams are you still investigating this? :)

**Review by corradio — APPROVED** [review]
I took the liberty of finalising some changes.

**Pull request merged**
