### PR TITLE
Fix for IN-KA parser

### PR DESCRIPTION
**Pull request by hboisgibault**
Fixes for the IN-KA parser.
Some small bugs where causing the parser to fail.
First bug is about date parsing and timezone.
Second one is about getting the difference between two arrow date objects.

### CODE REVIEW

**Comment by gwpicard** [comment]
It looks like these changes are failing the test:

```
======================================================================
ERROR: test_fetch_production (test_IN_KA.Test_IN_KA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/parsers/test/test_IN_KA.py", line 38, in test_fetch_production
    data = IN_KA.fetch_production('IN-KA', self.session)
  File "/home/circleci/project/parsers/IN_KA.py", line 41, in fetch_production
    india_date_time = IN.read_datetime_from_span_id(html, 'lbldate', 'M/D/YYYY h:mm:ss')
  File "/home/circleci/project/parsers/lib/IN.py", line 9, in read_datetime_from_span_id
    return get(india_date_time, format + " ZZZ")
  File "/home/circleci/project/.venv/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.7/site-packages/arrow/factory.py", line 247, in get
    args[0], args[1], normalize_whitespace
  File "/home/circleci/project/.venv/lib/python3.7/site-packages/arrow/parser.py", line 244, in parse
    self._parse_token(token, value, parts)
  File "/home/circleci/project/.venv/lib/python3.7/site-packages/arrow/parser.py", line 389, in _parse_token
    parts["tzinfo"] = TzinfoParser.parse(value)
  File "/home/circleci/project/.venv/lib/python3.7/site-packages/arrow/parser.py", line 584, in parse
    'Could not parse timezone expression "{}"'.format(tzinfo_string)
arrow.parser.ParserError: Could not parse timezone expression "PM"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/parsers/test/test_IN_KA.py", line 47, in test_fetch_production
    self.fail("IN_KA.fetch_production() raised Exception: {0}".format(ex.message))
AttributeError: 'ParserError' object has no attribute 'message'

----------------------------------------------------------------------
```

**Comment by hboisgibault** [comment]
I updated the mock pages used in the tests and the corresponding test value.
The date format in the data changed, that is why the parser was failing.

**Comment by skovhus** [comment]
`poetry run test_parser 'IN-KA' production` now returns:  

```                                                                                          
2021-09-10 09:03:27,870 DEBUG    urllib3.connectionpool         Starting new HTTP connection (1): kptclsldc.in:80
2021-09-10 09:03:28,698 DEBUG    urllib3.connectionpool         http://kptclsldc.in:80 "GET /StateGen.aspx HTTP/1.1" 301 157
2021-09-10 09:03:28,706 DEBUG    urllib3.connectionpool         Starting new HTTPS connection (1): kptclsldc.in:443
2021-09-10 09:03:30,471 DEBUG    urllib3.connectionpool         https://kptclsldc.in:443 "GET /StateGen.aspx HTTP/1.1" 200 5124
2021-09-10 09:03:30,563 DEBUG    urllib3.connectionpool         Starting new HTTP connection (1): kptclsldc.in:80
2021-09-10 09:03:31,345 DEBUG    urllib3.connectionpool         http://kptclsldc.in:80 "GET /StateNCEP.aspx HTTP/1.1" 301 158
2021-09-10 09:03:31,353 DEBUG    urllib3.connectionpool         Starting new HTTPS connection (1): kptclsldc.in:443
2021-09-10 09:03:33,079 DEBUG    urllib3.connectionpool         https://kptclsldc.in:443 "GET /StateNCEP.aspx HTTP/1.1" 200 3441
Parser result:
{'datetime': datetime.datetime(2021, 10, 9, 12, 27, 36, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Kolkata')),
 'production': {'biomass': 115.0,
                'coal': 591.0,
                'gas': 0.0,
                'geothermal': 0.0,
                'hydro': 1659.0,
                'nuclear': 0.0,
                'oil': 0.0,
                'solar': 2893.0,
                'unknown': 10.0,
                'wind': 2718.0},
 'source': 'kptclsldc.in',
 'storage': {'hydro': 0.0},
 'zoneKey': 'IN-KA'}
---------------------
took 5.30s
min returned datetime: 2021-10-09T06:57:36+00:00 UTC
max returned datetime: 2021-10-09T06:57:36+00:00 UTC  -- OK, <2h from now :) (now=2021-09-10T07:03:33.111212+00:00 UTC)
2021-09-10 09:03:33,111 WARNING  test_parser                    Validation failed @ 2021-10-09 12:27:36+05:30: Data from IN-KA can't be in the future, data was 2021-10-09T12:27:36+05:30, now is 2021-09-10T07:03:33.111755+00:00
```

@gwpicard I'll let you merge if the values looks good to you.

**Review by skovhus — APPROVED** [review]
@hboisgibault thanks for fixing this! The data now looks correct and I've verified the production data with our historical data. This should be back on the live map soon.

**Pull request merged**
