### PR TITLE
US-BPA Capacity Update

### PR DESCRIPTION
**Pull request by nessie2013**
No source update required

### CODE REVIEW

**Comment by robertahunt** [comment]
Hey @nessie2013 , could you confirm that you got the data from https://transmission.bpa.gov/business/operations/Wind/baltwg.aspx? I don't see where they list solar capacity there.

**Comment by alixunderplatz** [comment]
biomass and wind capacity lower, what's the reason?

**Comment by robertahunt** [comment]
@alixunderplatz Seems like some wind farms changed balancing authorities in 2018: https://transmission.bpa.gov/business/operations/wind/WIND_InstalledCapacity_PLOT.pdf
I would assume the same for biomass (at least the numbers here match what BPA reports their capacity to be).

**Comment by robertahunt** [comment]
For the records: https://transmission.bpa.gov/business/operations/wind/WIND_InstalledCapacity_LIST.pdf looks like they spun some of their wind farms off into the AVRN balancing authority

**Comment by nessie2013** [comment]
Yup I don't know where that solar came from, was a mistake so I removed it

**Pull request merged**
