### PR TITLE
Spanish mainland data from REE #2203: In progress

### PR DESCRIPTION
**Pull request by liacds**
Hi, I think I did most of the job, but I have some questions:
1. is there a convention for creating zone_keys? 
2. to make this parser I looked at ES_IB and ES_CI and they found oil differently and I am a bit confused which one is right

### CODE REVIEW

**Comment by robertahunt** [comment]
Hi @liacds , Sorry about the late reply getting back to you. There isn't one defined method of creating zone keys, so I think calling it ES-P has you have done, is alright.

This is data for mainland spain, is that correct? We currently get data from ENTSOE - I have been trying to find time to dig into the differences between these two datasources, but it is difficult. If you have time to quantify the difference between this data and what we get from ENTSOE, that would be great!

Otherwise, it is always nice to have extra parsers, but we wouldn't switch to a new one without a quantifiable reason.

**Comment by martincollignon** [comment]
Hi @liacds would you have time to look at the differences between the two data sources?

**Comment by liacds** [comment]
Hi, sorry for not responding earlier. I haven't looked at differences yet, but I can do it this week.

**Comment by corradio** [comment]
Hi @liacds ,
Unfortunately we need parsers that are able to fetch historical data (like ENTSOE's)
Do you know if REE allows that?

**Comment by liacds** [comment]
Hi @corradio, 
https://github.com/tmrowco/electricitymap-contrib/issues/2203 this is the issue that I worked on and it says it does.

**Comment by corradio** [comment]
> Hi @corradio,
> #2203 this is the issue that I worked on and it says it does.

In that case, are you able to edit the parser to fetch historical data as well? Then we will be able to gather a sample historical dataset of REE and ENTSOE to compare them to double check the data quality of REE is superior!
Thanks,

Olivier

**Comment by liacds** [comment]
No, sorry I don't want to do that

**Comment by corradio** [comment]
In this case I will unfortunately have to close the PR. I hope someone else can add the historical part and build on your work!

Olivier

**Pull request closed without merging**
