### PR TITLE
add real-time data sources Australia

### PR DESCRIPTION
**Pull request by KabelWlan**
I added the real-time data source for Flinders Island, Rottnest Island and OpenNEM.

Theorecially we could delete the other sources 
- AREMI National Map
- AEMO
- Australia (distributed solar generation)
- Australia (South Battery)

Those are not in use anymore if I see that correct.

What do you guys think?

### CODE REVIEW

**Review by FelixDQ — COMMENTED** [review]
Thank you @KabelWlan :-)

Yes, it would be great if you also removed the data sources that are no longer in use.

Thanks!

**Comment by KabelWlan** [comment]
Thank you for your feedback. I deleted the old ones.

**Review by FelixDQ — APPROVED** [review]
🙌

**Comment by bch920** [comment]
@KabelWlan Should this enable real time access for WA as well ? Currently WA doesn't seem to have live data. I've tried to look through the Parser /logs ( I'm not to technical)  but couldn't see anything obviously wrong.

**Comment by FelixDQ** [comment]
@bch920 this PR is only a documentation change :-) 

I think the problem with WA is that we get delayed data from OpenEM.

**Pull request merged**
