### PR TITLE
Add US_TX production parser

### PR DESCRIPTION
**Pull request by typicalTYLER**
I've added a basic parser for ERCOT/US_TX as part of #1160 

Points to note:
- Didn't take into account the exchanges from this data (I can possibly add on later)
- There were multiple access points to ercot APIs used, I just put the most accessible one in the sources
- There's fluctuating total capacity in the real time data, I just sampled it at some point and put it in the capacities, not sure if this is best practice
- I'm new to this (and live in Texas :)) and guessed about a couple different things, let me know if I've implemented anything incorrectly and I can fix!

### CODE REVIEW

**Comment by corradio** [comment]
Hi @typicalTYLER ,

Thank you for submitting this. From what I see the production mix only contains wind/solar.
In order to be show on the electricityMap, we need to be able to show a representative picture of the mix that sums up to the total production. Are you able to fetch the rest of the production? Maybe even putting it inside an "unknown" category?

Olivier

**Comment by systemcatch** [comment]
Very nice @typicalTYLER! Can you post some output from your parsers?

**Comment by typicalTYLER** [comment]
@systemcatch: here's the output from the parsers currently:
`fetch_production() ->
{'source': 'ercot.com', 'datetime': datetime.datetime(2019, 3, 15, 8, 25, tzinfo=tzfile('/usr/share/zoneinfo/US/Central')), 'production': {'wind': 9129.14, 'solar': 48.5}, 'zoneKey': 'US-TX', 'storage': {}}
fetch_consumption() ->
{'datetime': datetime.datetime(2019, 3, 15, 9, 29, 35, tzinfo=tzfile('/usr/share/zoneinfo/US/Central')), 'consumption': 39580.0, 'zoneKey': 'US-TX', 'source': 'ercot.eu'}`

(fortunately I live in the Texas so I'm not geo blocked by default)

@corradio: I was originally thinking unknown production was calculable from this API, but got a little confused by the terminology: image

Is the unknown production just calculated from: total demand - solar - wind - dc_ties? I also wasn't sure what the sign on the dc_ties implied (in vs out). Is the hourly data from the load report the same thing as the total demand from here as well?

**Comment by typicalTYLER** [comment]
I've added the unknown production now, under the assumption that production + DC tie flows have to meet demand. Here's a sample output:
`fetch_production() ->
{'datetime': datetime.datetime(2019, 3, 15, 10, 40, tzinfo=tzfile('/usr/share/zoneinfo/US/Central')), 'production': {'solar': 1206.88, 'unknown': 25490.770000000004, 'wind': 11990.35}, 'source': 'ercot.com', 'storage': {}, 'zoneKey': 'US-TX'}
fetch_consumption() ->
{'consumption': 38876.0, 'datetime': datetime.datetime(2019, 3, 15, 11, 40, 35, tzinfo=tzfile('/usr/share/zoneinfo/US/Central')), 'source': 'ercot.eu', 'zoneKey': 'US-TX'}`

The math seems to cause a floating point error, not sure how y'all want me to handle that. Maybe round to two decimal places or just pass it as is.

**Comment by corradio** [comment]
Looks great. Do anyone know what the average mix of "unknown" is? Do they have hydro or is it exclusively fossil-based?

**Comment by typicalTYLER** [comment]
Looks like we have some Nuclear and some Hydro: image from here https://www.eia.gov/state/?sid=TX#tabs-4

Looks like this data is just from November though

**Comment by typicalTYLER** [comment]
There's also this chart, but the data is older. Maybe it's more accurate for accounting for unknown, since I'm not sure what "net" electricity generation means in the previous graph. The large jump in fossil fuels is probably due to it accounting for the summer electricity production, which is a lot higher in magnitude due to how hot it gets here in Texas and how much air conditioning is used. image

**Comment by typicalTYLER** [comment]
Found a better source and updated the unknown estimates and capacities: http://www.ercot.com/content/wcm/lists/172484/ERCOT_Quick_Facts_01.17.19.pdf

**Comment by corradio** [comment]
Looks good to me. @systemcatch can you help doing another pass just to be sure?

**Comment by typicalTYLER** [comment]
I was going to try to make the change on my phone, as I'm on vacation abroad currently and can't access a computer, but it looks like maybe my fork has a different file location for that file, so maybe it's out of date or something not trivial enough to do on my phone easily. Would it be possible for one of y'all to make the final change?

**Comment by systemcatch** [comment]
@typicalTYLER I've made the change and will now merge this in, thanks again for the big contribution!

**Pull request merged**
