### PR TITLE
Fix IN-AP (Andhra Pradesh) parser

### PR DESCRIPTION
**Pull request by blackleg**
Fix IN-AP parser, related to: https://github.com/tmrowco/electricitymap-contrib/issues/1982

### CODE REVIEW

**Comment by corradio** [comment]
@robertahunt on this repo you can just merge once you approve the PR

**Comment by systemcatch** [comment]
Seems like a permission issue that is causing the circleci failure.
```shell
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```

**Comment by corradio** [comment]
I think it's because @robertahunt merged master on @blackleg 's fork, and thus circle ci tries to use  @robertahunt 's credentials.
@blackleg are you able to merge master on your branch ?

**Comment by blackleg** [comment]
@corradio  I rebased master branch into my pull request and CircleCI isn't work.

**Comment by corradio** [comment]
very weird. I'll just merge for now.

**Pull request merged**
