### PR TITLE
Fix negative unknown production in NL

### PR DESCRIPTION
**Pull request by PaulCornelissen**
Proposed fix for #2638 

This ignores consumption that is reported when fetching production values.

### CODE REVIEW

**Comment by FelixDQ** [comment]
Awesome! I just sent an email to ENTSO-E to be 100% sure that this is the correct way to interpret the data :-)

**Comment by PaulCornelissen** [comment]
I also did that this morning after your message, but hadn't reported back here since I'm at work now... So maybe we get 2 answers 😀

**Comment by PaulCornelissen** [comment]
I just got an answer back which confirms my thoughts:

> Dear Paul,
> 
> Thank you for your email.
> Regarding the consumption of generation units, the manual of procedures for the Actual Generation per Generation Unit says:
> "Average of all available instantaneous net power output values in each Market Time Unit.
> A generation unit could never be considered as a consumption unit"
> For some units, in addition to their generation activity they may consume energy. One explanation could be the fact it is an industrial site and consume energy for their activity. However, if they also sell electricity, they are seen as a generation unit and since a generation unit can never be considered as a consumption unit, their consumption is reported in the Actual Generation section.
> If other countries have values close to 0, it must means that their generation units are not conjugated with a consumption source of energy.
> 
> I hope the above helps.
> Best regards,

So consumption reported under actual production is consumption at the site of a producer, so it should not be subtracted from that production value. Rather it is consumption that is not reported as consumption when using fetch_consumption, so it should really be added there to get a good view of consumption in a country. In the case of NL (where unknown is calculated as the difference between consumption and known production) this should actually be added to unknown production.

**Comment by PaulCornelissen** [comment]
@FelixDQ Can this be merged?

**Review by FelixDQ — APPROVED** [review]
Yes, sorry. Let's merge :-)

@PaulCornelissen would you mind opening an issue stating the remaining TODO's regarding adding the self-consumption to `fetch_consumption`, and the special case for NL?

**Pull request merged**
