### PR TITLE
Update TR 🇹🇷  parser: add hydro storage

### PR DESCRIPTION
**Pull request by Manu1400**
Fix a mistake : _barajli_ mean _hydro storage_

source: https://ytbsbilgi.teias.gov.tr/ytbsbilgi/frm_istatistikler.jsf (in english version)

### CODE REVIEW

**Comment by KabelWlan** [comment]
Are you sure that this is pumped hydro storage? [IRENA](https://www.irena.org/publications/2021/March/Renewable-Capacity-Statistics-2021) doesn't report any hydro storage and I think that somewhere in zones it says that Turkey doesn't have any pumped hydro storage.

**Comment by jarek** [comment]
Maybe their English version of the page uses "hydro storage" in the sense of seasonal storage behind a dam? (_barajli_ = _barrage, dam_?) That would seem to complement the other hydro which is "run of river" in their English page.

**Comment by gwpicard** [comment]
Hey @Manu1400 - loving the initiative here as well! Let us know if you have any updates and for your other PRs 😄

**Comment by gwpicard** [comment]
Closing this PR for now because of inactivity. Feel free to re-open it addressing the suggestions!

**Pull request closed without merging**
