### PR TITLE
Poland Capacity Update

### PR DESCRIPTION
**Pull request by nessie2013**
Used the IRENA renewable data and some updated numbers from ENTSO-E

### CODE REVIEW

**Comment by wojciej** [comment]
Hello, I need to disagree with this change and here are the reasons :

- gas capacity was changed from "gas": 2812, to "gas": 2540,  - and this is cause the lower value does not include Fossil Coal-derived gas | 272.
As this was agreed in here https://github.com/tmrowco/electricitymap-contrib/pull/1764 we should add those two values together

- hydro power and hydro storage power was changed from
      "hydro": 605,
      "hydro storage": 1780,
to 
      "hydro": 968,
      "hydro storage": 1423,
In total its all the same, its just that IRENA raport qualify those two differently than ENTSOE

- wind was changed from
      "wind": 5953
to
      "wind": 5917
And this is lower value is in aligned with what URE provides with its data
https://www.ure.gov.pl/download/9/10905/mocIVkw2019.pdf
however this does not include private generation sources that are small enough that do not need to be concessioned like private PV on a private home in Poland

The only data change I could agree with is the biomass - and this is even higher as per my current update and pull request and this confirms the URE data I have linked above. 

Please decide what to do in this situation, as this update puts confusion and inconsistency to the previous agreements.

**Comment by jarek** [comment]
I'm not really familiar with the Polish energy market. Per #1764 yeah gas should include coal-derived gas. @nessie2013 any thoughts?

**Comment by wojciej** [comment]
Hi Jarek, 
Thanks for your reply. 
I will include them in 2446 I just wanted to wait couple days to see if @nessie2013 would reply to this thread cause I dont want to play hide and seek with the data, changing them back and forth. I would rather understand the reasoning here.

**Comment by wojciej** [comment]
Since we did not get any reply to this thread from @nessie2013 even tho the user has been active (pull request has been created on 5th of May #2474) I will revert all the changes done in this pull request.

**Pull request merged**
