### PR TITLE
Fix incorrect data source url in Moldova parser

### PR DESCRIPTION
**Pull request by lgrigoryeva1**
There was an issue with the Moldova parser MD.py, where it failed to fetch data from the specified URL. 
Turns out the data source url was missing `.php` at the end. 
The correct url is: http://www.moldelectrica.md/utils/load4.php

### CODE REVIEW

**Comment by lgrigoryeva1** [comment]
Thinking if I should have added some error message if the parser can't access the data in case this happens again in the future?

**Review by FelixDQ — COMMENTED** [review]
Thanks @lgrigoryeva1! Yes adding a better error message is probably a good idea if you want to do that. Otherwise, the only thing left is adding yourself to the contributor list

**Comment by lgrigoryeva1** [comment]
@FelixDQ Done. Let me know if there's something else :)

**Review by FelixDQ — APPROVED** [review]
Let's merge 🎉

**Pull request merged**
