### PR TITLE
Update wind capacity for Norway

### PR DESCRIPTION
**Pull request by Gazer75**

### CODE REVIEW

**Comment by tth4vb** [comment]
@Gazer75 thanks for this :) could you just reference which source you're using for these capacity updates?

**Comment by tth4vb** [comment]
@Gazer75 thanks for this :) could you just reference which source you're using for these capacity updates?

**Comment by Gazer75** [comment]
Same as before. NVE should be listed

**Review by tth4vb — APPROVED** [review]

**Comment by tth4vb** [comment]
Got it, thanks for clarifying :)

**Pull request merged**
