### PR TITLE
New parser for IN-UT

### LINKED ISSUE #1465: Add Uttarakhand (India) IN-UT
Digging through the Indian "state load despatch centres" I found real-time data for generation in the state of Uttarakhand.

http://uksldc.in/real-time-data.php

They seem to have domestic generation from gas and hydro, although this seems to cover only ~50% of IN-UT's recent demand, so they have quite high imports. The state seems to own shares
of central power stations in Uttar Pradesh, listed under CSGS. So a share of these is produced for IN-UT as well, but in IN-UP (I think we probably cover all of this for UP already).

image

It's possible to include interconnections with two neighbouring states (this would be first time for India) with Uttar Pradesh as well as Himchal Pradesh (we don't have generation for this state atm).

I compared data from the tie line table with these two maps on this site:
http://uksldc.in/power-map

For the interconnectors with Uttar Pradesh, these are the tie lines that need to be considered when summing up IN-UP->IN-UT (main flow should usually be towards Uttarakhand).
Note that the line don't follow a strict pattern like "outside->inside". The **BOLD TIE LINES** point from Uttarakhand to Uttar Pradesh, so these lines should be accounted negatively for the mentioned direction IN-UP->IN-UT when balancing.

Interconnectors with Uttar Pradesh:

400KV MORADABAD-KASHIPUR
**400KV KASHIPUR-BARIELY 2
400KV KASHIPUR-BARIELY 1
400 KV POHANA-MUZZAFFARNAGAR
220KV ROORKEE-NARA
220KV KHODRI-SHARANPUR2
220KV KHODRI-SHARANPUR1**
220KV BAREILLY-PANTNAGAR
**132KV SITARGANJ-DOHANA
132KV RAMGANGA-DHAMPUR
132KV MAHUAKHEDAGANJ-THAKURDWARA
132KV KHATIMA-PILIBHIT**

Interconnectors with Himachal Pradesh IN-HP->IN-UT (again, when balancing, **bold** is negative, not bold is positive):

**220KV KHODRI-MAJRI**
132KV GIRBATTAI-KULHAL

From the two columns, only the "MW" column must be used, the "MVA" is just for reactive power which is unimportant for us.

There also is a 132 kV line towards nepal indicated on one of the maps, but, unfortunately, it is not listed in the tie line table.

### PR DESCRIPTION
**Pull request by lorrieq**
* Exchanges with IN-HP and IN-UP

* Production values for gas and hydro

closes #1465

### CODE REVIEW

**Comment by lorrieq** [comment]
Hey guys, check out the [sample output](https://github.com/tmrowco/electricitymap/files/2139395/in_ut_sample.txt).

The most important areas for review is the correctness of the interconnection summation of all the tie lines for each exchange and the rotation of the new exchanges in `exchanges.json` as they're currently set to 0.

**Comment by systemcatch** [comment]
You're on a roll @lorrieq !

Can you get this running locally so we can check the exchanges look ok.

**Comment by corradio** [comment]
This looks terrific!

**Comment by lorrieq** [comment]
Thanks @alixunderplatz for the rotations!

I won't be able to get it running locally until late next week (computer not with me). Can anybody else check the exchanges look ok?

**Comment by lorrieq** [comment]
Hey guys, exchanges are looking nice on the map. Do we know anything about the installed capacity of gas and hydro or do we just leave as is at 0 in `zones.json`? I think we're ready to merge this other than that.

screen shot 2018-07-10 at 10 04 07

**Comment by corradio** [comment]
Great job! Just FYI, if we're unsure about the capacity, better leave them out of zones.json (or set to null), instead of 0.

**Comment by corradio** [comment]
Can you update the README with the data source you used?
After that we can merge (exciting to have our first Indian exchanges!)

**Comment by lorrieq** [comment]
Great!

**Pull request merged**
