### PR TITLE
Barry Referral, UI concept

### PR DESCRIPTION
**Pull request by ovbm**
to do:
- [x] limit to DKK panel
- [x] geolocation
- [x] add real link

### CODE REVIEW

**Comment by ovbm** [comment]
screenshot 2018-11-13 at 15 21 34

**Comment by corradio** [comment]
Ref https://github.com/tmrowco/electricitymap/issues/1129

**Comment by corradio** [comment]
Very cool, very cool. Thanks. I'll take over from here.

**Comment by ovbm** [comment]
I had already started with the zone selection before I read your message. It's implemented with returning a static element for zones DK1 and DK2 now, but it could be adapted to be more dynamic.

**Comment by corradio** [comment]
Don't merge - we need the proper final message from Barry.

**Pull request merged**
