### PR TITLE
Added US zones to exceptions

### PR DESCRIPTION
**Pull request by robertahunt**
Some of the new US zones do not have coal, oil, gas, or unknown production, but were not yet added to quality checks exceptions. This adds them.

### CODE REVIEW

**Comment by corradio** [comment]
Just to make sure: is it because it's not present in the data, or is it because they don't have physical assets (i.e. capacity is 0)?

**Comment by robertahunt** [comment]
It is slightly different in each case, but it is primarily because these BAs only have hydro capacity.

**Comment by corradio** [comment]
Approving, but just to make sure I understood correctly: we agree that all those BAs have negligible fossil fuel (oil, gas, coal) capacity right? If not, then we should quickly discuss.

**Comment by robertahunt** [comment]
EIA is not reporting any fossil fuel capacity for these zones. It is possible they have some fossil fuels that are not reported by EIA, but I find that unlikely.

**Comment by corradio** [comment]
got it

**Pull request merged**
