### PR TITLE
Split ES-IB [work in progress]

### PR DESCRIPTION
**Pull request by alixunderplatz**
This is an attempt for a parser splitting the generation on the Balearic islands.
ref #1347 
 
As usual, feel free to comment and improve diectly, so we can move on to the next steps.

I copied and adapted most of the code from ES_CN. 

Some things are commented out (and in In fetch production, there is no "logger=logging.getLogger(__name__)" like in ES-CN) because I had local issues and I'm far, far away from being an expert in terms of Python ;)

### CODE REVIEW

**Comment by systemcatch** [comment]
First pass things seem generally correct. CircleCI is failing due to the tests being out of date, easy fix there.

**Comment by systemcatch** [comment]
Actually I was wrong about the tests being an easy fix, there's more changes required than I thought. @blackleg do you want to have a try at altering them?

**Comment by corradio** [comment]
@blackleg are you able to help here?

**Comment by blackleg** [comment]
Hi @corradio, I can help with it. Could you divide Balearic islands shape into islands?

**Comment by corradio** [comment]
I think @systemcatch has a good handle on this - else I can help.

**Comment by corradio** [comment]
No worries, you can do `git revert` from the the PR (which will create a
commit that cancels the previous commit).
I suggest you copy/paste the file to a new branch/PR. Write us on slack
#electricitymap else, and we'll help!

Olivier

**Comment by corradio** [comment]
Closing this in favor of #1580

**Pull request closed without merging**
