### PR TITLE
[DE] Update zones.json

### PR DESCRIPTION
**Pull request by chiefymuc**
2021 Update from Fraunhofer:
https://energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE&sum=1&partsum=1&stacking=stacked_absolute&expansion=installed_power

### CODE REVIEW

**Review by Bohne13 — APPROVED** [review]
- numbers are checked and good!
- nice to see battery storage is added to the list!

**Comment by madsnedergaard** [comment]
Would you mind updating the link in DATA-SOURCES.md? The current one is broken :)

**Comment by chiefymuc** [comment]
Hello,

so I looked a bit deeper at the data. Mainly there are 2 sources:

Fraunhofer (it says 2021, but the no exact date)
https://energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE

Bundesnetzagentur (2021-01-19, pretty current)
https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html

They have a bit different categories and also differing values, I've listed it here habing in mind the ENTSOE parser mapping, but I have some I'm not sure how to add up:


Fraunhofer | in GW
battery storage | 0,28
biomass total | 8,55
biomass | 8,55
coal total | 43,95
brown coal | 20,25
hard coal | 23,70
gas | 30,50
hydro total | 4,85
river run | 3,87
dams / reservoir | 0,98
hydro storage (pumped) | 9,81
nuclear | 8,11
oil | 4,38
solar | 54,52
Wind Total | 62,59
Wind onshore | 54,82
Wind offshore | 7,77


Bnetz | in MW
battery storage| 279
biomass total | 10.378
biomass | 8.597
waste | 1.781
coal total | 33.932
brown coal | 17.772
hard coal | 16.160
gas | 26.948
geothermal | 47
hydro total | 4.856
river / run water | 3.871
dams / reservoir (without pumped) | 985
hydro storage / pumped | 9.654
nuclear | 8.114
mineral oil | 2.556
solar | 51.479
Wind | 61.460
wind (Onshore) | 53.719
wind (Offshore) | 7.741

Here the ones I'm not sure how to group:
landfill gas (Deponiegas) | 173
pit/mining gas (Grubengas) | 176
sewage treatment plant gas (Klärgas) | 159

multiple sources (non-renewable) - Mehrere Energieträger (nicht erneuerbar) | 189
other sources (non-renewable) - Sonstige Energieträger (nicht erneuerbar) | 3.134
unknown sources (non-renewable) - Unbekannter Energieträger (nicht erneuerbar) | 0

Note that there are significant differences between Fraunhofer and Bnetz in the gas and especially coal. I tend to trust the Bnetz more, as some coal plants have been shut down, which should be reflected here.

Regarding the grouping, I would add the landfill/mining/sewage gas to gas, as it is likely methane gas so should be somewhat similar to natural gas regarding CO2.

The others could be summed up under "unknown"?

What is your opinion?

**Comment by chiefymuc** [comment]
Another comment:

The Bnetz does not list reserves under the "active" plants, but it seems that Fraunhofer does. When I take all reserves etc into account from the BNetz list, it looks like this:


battery storage | 279
biomass total | 10.440
biomass | 8.610
waste | 1.830
coal total | 39.164
brown coal | 20.230
hard coal | 18.933
gas | 30.502
geothermal | 47
hydro total | 4.856
Running / river water | 3.871
Reservoir / dams | 985
hydro storage (pumped) | 9.814
nuclear | 8.114
oil | 4.375
solar | 51.479
unknown |  
wind | 61.474
wind onshore | 53.733
wind offshore | 7.741

landfill gas | 173
mining/pit gas | 176
waste water treatment gas | 159

multiple sources | 189
other sources | 3.134
unknown sources | 0

There are still differences in biomass (because Fraunhofer does not count the waste) of ~2GW. Hard coal ~4.7GW less on Bnetz. solar ~3GW on Bnetz. Wind ~ 1.1GW less on Bnetz.

I tend to take the Bnetz values (including reserves) that should cover most of it.

**Comment by corradio** [comment]
@Bohne13 are you able to advise?

**Comment by Bohne13** [comment]
I would merge the actual numbers from Fraunhofer ISE for now.
I do know the fact that there are different numbers between Fraunhofer, Bundesnetzagentur and entsoe.

Is a question of trust and background research what sources are use to compile the numbers.
In my case I trust the science workers from Fraunhofer.
When it comes to realtime data they all use the entsoe API.

Conclusion:
- For consistency, use all the numbers from Entsoe.
- More up to date 'Instalated Capacity' Fraunhofer is your main choice.
- Fore realtime data, entsoe is the only way wit a proper API

I hope this an appropriate answer 🙂

**Comment by veqtrus** [comment]
If landfill gas is a byproduct that would otherwise be released in the atmosphere then burning it to CO2 could have negative carbon equivalent intensity, as methane is far worse greenhouse gas. Reality is more nuanced though, so I would group it with biomass.

**Comment by madsnedergaard** [comment]
Thanks for the inputs everyone, let's stick to Fraunhofer :)
Would you mind updating the link in DATA_SOURCE.md with the one from your PR description?

**Comment by chiefymuc** [comment]
OK, I did update the link in DATA_SOURCE.md but accidentally it is now another PR.. Sorry, I'm not very familiar with github.

I also added my name to contributers as the bot asked me to.

**Review by Bohne13 — APPROVED** [review]

**Review by Bohne13 — APPROVED** [review]

**Comment by madsnedergaard** [comment]
Brilliant, thanks - now merged! 💪

**Review by madsnedergaard — APPROVED** [review]

**Pull request merged**
