### PR TITLE
Production capacities for Norway

### PR DESCRIPTION
**Pull request by Gazer75**
Update production capacities for Norway #1729 
Values for wind and hydro calculated from NVE database. ENTSOE values were very low.

### CODE REVIEW

**Comment by systemcatch** [comment]
Hey @Gazer75, thanks for the contribution. Couple of things need to be tweaked before we can merge this. Can you update the readme source list with the new Norway regions. Also we tend to only set capacities to zero when we are absolutely sure there are no generators of that type.

**Comment by Gazer75** [comment]
So new at all this. Is there some way I can edit that file and add it here?
As I edited about the wind and hydro is basically from the databases I listed in #1729

**Comment by Gazer75** [comment]
Unless you consider district heating in the calculations here, then I can say with certainty that we have only hydro and wind with gas as backup.
Where the 5MW of gas listed in NO2 at ENTSOE is coming for I have no clue. 
Gas value for NO5 should probably be set to 0 unless they postponed the planned shutdown of Mongstad at end of 2018. 
In NO4 there is a mobile backup gas plant at Tjeldbergodden which is why there is 270MW listed.

**Comment by brunolajoie** [comment]
Please find below what our database has registered as max instantaneous output in 2018 for each NO zone. 

We'll have conflicts for each zones, where output will be higher than reported capacity (especially for gas). It will report more than 100% capacity factor. Not such a big deal, but that should deserve a bit of investigation i'd say!

NO1
biomass          NaN
coal             NaN
gas             29.0
hydro         2959.0
nuclear          NaN
oil              NaN
solar            NaN
wind             0.0
geothermal       NaN
unknown         91.0

NO2
biomass          NaN
coal             NaN
gas              7.0
hydro         9440.0
nuclear          NaN
oil              NaN
solar            NaN
wind           566.0
geothermal       NaN
unknown        404.0

NO3
biomass          NaN
coal             NaN
gas            110.0
hydro         3765.0
nuclear          NaN
oil              NaN
solar            NaN
wind           350.0
geothermal       NaN
unknown        263.0

NO4
biomass          NaN
coal             NaN
gas            229.0
hydro         4295.0
nuclear          NaN
oil              NaN
solar            NaN
wind           250.0
geothermal       NaN
unknown         33.0

NO5
biomass          NaN
coal             NaN
gas            143.0
hydro         6602.0
nuclear          NaN
oil              NaN
solar            NaN
wind             0.0
geothermal       NaN
unknown         29.0

**Comment by Gazer75** [comment]
I assume these production numbers are also coming from ENTSOE?
I could contact Statnett or something and see if someone is willing to explain the numbers reported

**Comment by brunolajoie** [comment]
ENTSOE yes!

**Comment by brunolajoie** [comment]
I think we can turst your capacity number more than our ENTSOE actual generation data.
I'm approving the PR as it is: what will have to be checked/changed in more our ENTSOE parser than your fixed capacity data!

**Pull request merged**
