### PR TITLE
Show header when map is loading

### PR DESCRIPTION
**Pull request by kocvrek**
Issue https://github.com/tmrowco/electricitymap-contrib/issues/2846. Header is visible when map is loading.

header-pr

### CODE REVIEW

**Comment by madsnedergaard** [comment]
Thanks for doing this! 💪 
On smaller screens the info-panel is "breaking" (should be full screen) when removing `position:fixed` here - would you mind trying to see if that can be fixed? :) 

Screenshot 2021-02-22 at 11 36 37

**Comment by kocvrek** [comment]
@madsnedergaard My bad. Working on it.

**Comment by madsnedergaard** [comment]
Hey @kocvrek, did you have time to fixing this? Let me know if I can be of any help :)

**Comment by kocvrek** [comment]
@madsnedergaard I'll try my best to find a solution and update this PR by the end of the week. I'll be in touch if I have any problems.

**Review by skovhus — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
