### PR TITLE
Detection of broken links between md

### PR DESCRIPTION
**Pull request by ajoga**
After doing the work manually of fixing links, and as suggested in https://github.com/tmrowco/electricitymap-contrib/pull/2693#pullrequestreview-501867595 I'm submitting this to avoid future toil.

The modifications of the heading and links in the README are a workaround for a bug in the tool that checks broken links where images in heading are making the check fail. Bug is opened but not yet fixed: remarkjs/remark-validate-links#59

### CODE REVIEW

**Comment by ajoga** [comment]
paging @FelixDQ since you're aware of the context of this work :)

**Review by FelixDQ — APPROVED** [review]
LGTM! I moved the badges to their own line, so they don't push the text.

Thanks for adding this :-)

**Comment by ajoga** [comment]
> LGTM! I moved the badges to their own line, so they don't push the text.

Whoops, good catch. Thanks!

**Comment by ajoga** [comment]
Thank you for the fast feedback loop @FelixDQ  :)

**Pull request merged**
