### PR TITLE
Update Austria (AT) Capacities

### PR DESCRIPTION
**Pull request by brandongalbraith**
Updates Austria (AT) capacities. Possibly closes https://github.com/tmrowco/electricitymap-contrib/issues/2389

data origin: [ENTSOE](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2020+00:00%7CUTC%7CYEAR&dateTime.endDateTime=01.01.2020+00:00%7CUTC%7CYEAR&area.values=CTY%7C10YAT-APG------L!BZN%7C10YAT-APG------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19)

image

Deviations from the ENTSOE data: 
* last remaining coal plant has been shut down, therefore no coal generating capacity (see https://github.com/tmrowco/electricitymap-contrib/issues/2389 for details) should be remaining.
* "waste", "other", and "other renewable" have been aggregated into "unknown" key

### CODE REVIEW

**Comment by brandongalbraith** [comment]
Thanks @alixunderplatz! I’ll update the PR.

**Comment by robertahunt** [comment]
print @brandongalbraith  to update the coal capacity in case you forgot

**Comment by brandongalbraith** [comment]
@robertahunt I did forget 🤦 pushing an update shortly.

**Comment by brandongalbraith** [comment]
@robertahunt Updates made, thanks again for the reminder, my apologies for the delay.

Based on feedback from @alixunderplatz:
[x] Coal capacity reverted from ```0``` to ```246```
[x] ```Waste``` recategorized into biomass

**Comment by robertahunt** [comment]
No worries! Thanks!

**Comment by robertahunt** [comment]
I'll just wait for @alixunderplatz  to approve.

**Pull request merged**
