### PR TITLE
Update data-source and add archive for moldova

### LINKED ISSUE #973: Moldova MD / emission factor for gas
@brunolajoie

In #926, I mentioned that electricity production from natural gas in *Moldova* happens with an efficiency of ~22%, which leads to CO2-emissions of ~1000 g/kWh for the gas units. However, this efficiency was based on numbers from 2008, but I don't think that more efficient gas units were put into operation in the past decade in MD.

Here's the [source for the efficiency](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjhvbnshpLYAhWIEVAKHaIIACQQFgguMAA&url=http%3A%2F%2Fget-moldau.de%2Fdownload%2Fpolicypapers%2F2010%2FGET%2520Moldova_PP%252001%25202010_en.pdf&usg=AOvVaw37WEhiS1RHEn9lR52Ono--) (page -3-) 
image

I used [this as source for the CO2 emissions](http://www.klimaneutral-handeln.de/php/kompens-berechnen.php#rechner): 

burning 1 kWh of natural gas leads to 220 g CO2 emissions.
So 220 g/kWh(thermal) / 22% = 1000 g/kWh(electrical).

If you think the data is precise, let's use a country specific factor for MD ;)

### PR DESCRIPTION
**Pull request by Impelon**
I noticed Moldova's biggest power plant was still listed as *unknown*, despite it being classified as *gas* in #973.
The problem is that #1380 just modified a value in an unused constant, so the change had no effect.

Regarding dafc431:
I've noticed that there is a new URL for the data-source (http://www.moldelectrica.md/utils/load5.php) and I redesigned the parser using it.
**The old URL seems to just be stuck at some point in time, hence why the data for Moldova is not updated at all!**
I've also added links to some additional documents explaining how the *CERS Moldovenească* power plant operates.
Notably I can confirm that in 2019 and 2020 the power plant still uses mostly gas (over 99%) as fuel:
http://moldgres.com/wp-content/uploads/2021/02/proizvodstvennye-pokazateli-zao-moldavskaja-gres-za-2020-god.pdf
(By searching for *Производственные показатели* aka. *Performance Indicators* on http://moldgres.com/ all available documents can be found. They are written in Russian, but I've been able to easily translate them using Google.)

Additionally this commit takes the renewable energy generation (solar + wind + biogas) in Moldova into consideration. With a capacity of around 3 MW it is quite low and not distinctly mentioned on the map or the `data_url`.
But it can easily be calculated as the difference between the total production and all other forms of production.
The values seem to match up with the values from https://moldelectrica.md/ro/activity/operative_info.
Unfortunately it is not mentioned how this renewable energy mix is composed exactly, so I attributed it all to *biomass*.
(The [presentation](http://en.fas.gov.ru/upload/other/National%20Agency%20for%20Energy%20Regulation%20(G.%20Pyrzy).pdf) mentioned in #926 would indicate that this is mostly biomass, but those figures do not add up with the current data from Moldelectrica anyways.)

In my fork I also added 0903c614d90f8ee530cbb175cd921dffb3b7501e, which represents the code I used to check what the csv-data from `data_url` actually represents. This uses the contents of the `display_url`, where the contents of the data-url are directly mapped to the represented map. In case the data fetched changes slightly in the future, but `display_url` and `data_url` work the same, the code from 0903c614d90f8ee530cbb175cd921dffb3b7501e could be used to update the parser again.
But I do not know how much it fits with the rest of the parser, so I chose not to include it in this PR. Do you have any recommendations on where to put this *maintanence*-code? 

Regarding beeb6ab2:
I added the archive-data used at https://moldelectrica.md/ro/activity/operative_info to the parser as well,
meaning the parser does now support `target_datetime` for past dates.
The data-url for the archive is https://moldelectrica.md/utils/archive2.php?id=table&type=html; various formats are supported and additionally other time-series with higher time-resolution (f.e. for the electricity mix) are supported by passing other numerical values for the id. (I only implemented fetching the table archive data, not for the higher resolution timeseries.)
The archive-data contains data from the end of 2018 to 2021 and ongoing.

Notably the archive also contains `planned` values for production, exchange and consumption. 
You can take a look at https://moldelectrica.md/ro/activity/operative_info to see how the planned values compare to the actual values.
The archive does not contain `planned` values for future dates, so I'm not sure if these values are what the `*_forecast`-methods should return. 
If desired, I could also quickly add implementations for `fetch_consumption_forecast`, `fetch_generation_forecast`, `fetch_exchange_forecast` using the archive to this PR.

Keep in mind, I do not know if the data for the correct timerange is returned when `target_datetime` is used; right now it returns all data for the given date, the time-component is ignored.

----------

This fixes #973.

### CODE REVIEW

**Comment by Impelon** [comment]
Forgot to change some variables, as I've made some last minute changes before. Should be ready for review now!

**Comment by Impelon** [comment]
The price could also be returned from https://moldelectrica.md/ro/activity/tariff, 
but it doesn't change, it is specified to be 0.145 RON / kWh by this law:
http://lex.justice.md/viewdoc.php?action=view&view=doc&id=360109&lang=1
So I don't think it would be worth writing a parser for it, since it may break before/when the price actually changes.

In their [2020 annual report Moldelectrica (page 51)](https://moldelectrica.md/files/docs/raport/RAPORT%20ANUAL%202020.pdf) also mention approved capacities for renewables and the de-facto capacities for additional power-sources connected to their grid, which are as follows:
* solar: 0.5 MW
* wind: 4.14 MW
* biogas: 3.6 MW
* combined heat and power: 13.4 MW
Unfortunately Moldelectrica does not seem to provide live-data on these.

**Comment by madsnedergaard** [comment]
This is awesome, thanks for doing this extensive research and work! 💪 
And great with historical data!

> But I do not know how much it fits with the rest of the parser, so I chose not to include it in this PR. Do you have any recommendations on where to put this maintanence-code?

We currently don't have a unified way of doing this. But maybe you could add a link to the commit or move the code to a Github Gist and add that link as a comment to the parser code? It's not ideal, but I think it could work for now :)

> The archive does not contain planned values for future dates, so I'm not sure if these values are what the *_forecast-methods should return.
> If desired, I could also quickly add implementations for fetch_consumption_forecast, fetch_generation_forecast, fetch_exchange_forecast using the archive to this PR.

The values are meant to be forecast for future dates, and it seems like that's not possible here - so no need to do that.

> price

It would actually be nice to save the price, so this graph has data:

Screenshot 2021-07-26 at 12 12 15

I think your suggestion of a function returning the static value (and a comment about why) is perfect for this use case - then it can easily be updated later if the price changes, instead of having a price-parser that might break.

---

And then one additional comment: 

You mention that coal production capacity of coal is 1600 MW, but the parser doesn't return any coal - is that correct, and are we potentially missing out on something? If the data isn't available, there's not much we can do - I'm just curious :)

**Comment by Impelon** [comment]
> You mention that coal production capacity of coal is 1600 MW, but the parser doesn't return any coal - is that correct, and are we potentially missing out on something? If the data isn't available, there's not much we can do - I'm just curious :)

I believe the coal-powered units are mostly unused, as the "Performance Indicators"-reports ([the one for 2020 is also linked above](http://moldgres.com/wp-content/uploads/2021/02/proizvodstvennye-pokazateli-zao-moldavskaja-gres-za-2020-god.pdf)) for the past few years indicate coal is rarely used as fuel. For example the exact fuel-ballance for 2020 was:
* gas: 99.94%
* coal: 0.01%
* oil: 0.05% 

Although it is not explicitly mentioned how the ratio is determined, and I can imagine that if it was by volume, pulverized coal would have a low ratio.

But considering that the CCGT and gas+oil units are virtually enough to meet Moldova's planned peak power demand of 905 MW today (and CERS Moldovenească currently produces slightly less than 800 MW), I do think that it is possible the coal units are mostly used as a reserve only.

Unfortunately there is no real way to tell, Moldelectrica's archive simply aggregates CERS Moldovenească's production together with the thermal power plants. And CERS Moldovenească only provides the "Performance Indicators"-reports.

On that note I also just noticed there does not seem to be a source mentioned in #926 that explicitly states the other smaller power-plants to be natural-gas powered.
But at least CET-1 and CET-2 do seem to be mostly gas-powered as indicated here: https://www.termoelectrica.md/en_US/despre/informatii-tehnice/
Should I add that as a source in README.md?

I think it will be hard to get the electricity-mix right for Moldova, I found some sources that specify that around 20% of Moldova's energy share is renewable, mostly from biogas. But Moldelectrica simply does not provide the data for this, maybe because it is not supplied to their grid, or because they are not the producer and hence they do not report on it.
I found this chart for Moldova's energy share (including heating) in 2020 from [here](https://www.enerdata.net/estore/energy-market/moldova.html):
image

> This is awesome, thanks for doing this extensive research and work! :muscle:
> And great with historical data!

Glad I could help! I'll implement all the other proposed changes and update the PR later today!

**Comment by madsnedergaard** [comment]
Thanks for the explanation!

> Should I add that as a source in DATA_SOURCES.md?
No need to update `DATA_SOURCES.md` :)


> I think it will be hard to get the electricity-mix right for Moldova, I found some sources that specify that around 20% of Moldova's energy share is renewable, mostly from biogas

We might not get it 100% accurate, but I think your work here is more than good enough - especially when the mix is mostly gas and some biomass as you found.

**Comment by Impelon** [comment]
> No need to update `DATA_SOURCES.md` :)

Oops, I saw that a bit late. 62d3664 can safely be ignored then!

According to https://www.cet-nord.md/en/transparent/tep, CET-Nord has a new capacity of 37 MW (previously 28,5 MW), so I also added that to the gas category, for a total of 66 (CET-1) + 240 (CET-2) + 37 (CET Nord) + 920 (CERS Moldovenească) = 1263 MW.

I also added `fetch_consumption`. Consumption was previously returned in `fetch_production`, but I figured it should be in the proper function, right?

Otherwise everything should be as discussed.

**Comment by Impelon** [comment]
@madsnedergaard If you wish I can remove 62d3664 via a rebase!

**Review by madsnedergaard — APPROVED** [review]
The data-source update is fine, this is overall great! 🥳

**Comment by Impelon** [comment]
Glad I could help 🎉

**Comment by madsnedergaard** [comment]
It's live! 💯 
Screenshot 2021-07-29 at 08 46 50

**Comment by Impelon** [comment]
Looks great! :smile: 
Although it seems the price does not work. It just says ? / MWh... 

Also I guess I forgot to scale up the price to MWh, I assume the price should be returned in MWh, although the [wiki-page](https://github.com/tmrowco/electricitymap-contrib/wiki/Building-a-new-parser#fetch_price) does not mention it.

So the price returned by `fetch_price` should be 145 and probably not a string, I guess that's why that does not work :sweat_smile:

**Comment by madsnedergaard** [comment]
> Looks great! 😄
> Although it seems the price does not work. It just says ? / MWh...
> 
> Also I guess I forgot to scale up the price to MWh, I assume the price should be returned in MWh, although the [wiki-page](https://github.com/tmrowco/electricitymap-contrib/wiki/Building-a-new-parser#fetch_price) does not mention it.

Good point - I have updated the wiki now to mention that price is per MWh :)

> So the price returned by `fetch_price` should be 145 and probably not a string, I guess that's why that does not work 😅

Whoops yeah, it should be a float it seems 😄 
Screenshot 2021-07-29 at 10 33 58

**Pull request merged**
