### PR TITLE
Clarify "gas" as "natural gas" in English

### PR DESCRIPTION
**Pull request by veqtrus**
~~"hydro storage" -> "pumped hydro storage",~~
"gas" -> "natural gas"

Suggested in #2707 and #2663.

### CODE REVIEW

**Review by Kongkille — COMMENTED** [review]
I do think both changes make sense but for pumped hydro storage, I am a bit afraid that the text will be too long to be properly displayed?

**Comment by tth4vb** [comment]
Agreed on pumped hydro - I think it's fine to use hydro storage. @veqtrus do you mind removing that change? then I think it's ok to merge

**Comment by veqtrus** [comment]
Would perhaps "pumped hydro" make sense? Otherwise we can just change gas.

**Comment by Kongkille** [comment]
I would argue that we should just change gas for now :)

**Review by Kongkille — APPROVED** [review]

**Comment by Gazer75** [comment]
Hydro storage to me is power stations with big reservoirs, so it was kind of confusing before I looked at the code and the data at ENTSOE.

**Pull request merged**
