### PR TITLE
capacity update Spain January 2021

### PR DESCRIPTION
**Pull request by KabelWlan**
I updated Spains generation capacity according to the newest report from the spanish grid operator. 

Source: https://www.ree.es/es/datos/publicaciones/boletines-mensuales/boletin-mensual-enero-2021
I used the file named "produccion" page "Data 1".

If this PR  gets approved PR #2873 could be closed since he used an older report.

### CODE REVIEW

**Comment by madsnedergaard** [comment]
Hey @KabelWlan, thanks for the update here! :)

Two things:

1. Maybe it's just my kindergarden level Spanish that is insufficient, but it seems like the data we have from REE (the [source listed in DATA_SOURCES](https://www.ree.es/es/datos/publicaciones/series-estadisticas-nacionales)) has slightly different numbers. Do you know why? :)

Screenshot 2021-02-18 at 09 52 35

2. If this new source is more accurate than the existing one, would you mind updating `DATA_SOURCES.md` to reflect the change? I guess we can just link to https://www.ree.es/es/datos/publicaciones/boletines-mensuales and not the specific month.

**Comment by KabelWlan** [comment]
Hi @madsnedergaard 
Yeah that's a good question. The data on the left of your screenshot is national, means all of the islands which belong to Spain (the Balearic and Canary Islands) are included. The numbers on the screenshot on the right are from mainland Spain. 

Since the national data doesn't correspond to the mainland spain data I think we could completely replace the source with the new one. What do you think?

**Comment by madsnedergaard** [comment]
> Hi @madsnedergaard
> Yeah that's a good question. The data on the left of your screenshot is national, means all of the islands which belong to Spain (the Balearic and Canary Islands) are included. The numbers on the screenshot on the right are from mainland Spain.
> 
> Since the national data doesn't correspond to the mainland spain data I think we could completely replace the source with the new one. What do you think?

Ah okay, thanks for the explanation. Since we have the islands separated, let's use the mainland only data then :) Will you update DATA_SOURCES.md?

**Comment by KabelWlan** [comment]
I changed the data source :)

**Review by madsnedergaard — APPROVED** [review]
🥳

**Comment by madsnedergaard** [comment]
Also, thanks for doing our pull request number 3000! 😮

**Pull request merged**
