### PR TITLE
Feedback Form with Github API [Demo]

### PR DESCRIPTION
**Pull request by GitMatze**
em_demo

Here's a demo of a feedback form that allows to post on GitHub directly from the site using the GitHub API.
See Issue: https://github.com/tmrowco/electricitymap-contrib/issues/2499

+GUI is fully functional
+API is fully functional
-It's not functionally integrated into the map ( when changing countries etc. )
-Right now it requires a Github Token exposed in the source code. You have to replace it with your own just like in this demo: https://github.com/GitMatze/githubAPI/blob/master/githubAPI.png

`feedbackform_class_syntax.js` is equivalent to  `feebackform.js`, just written in class syntax

### CODE REVIEW

**Comment by corradio** [comment]
Hi @GitMatze ,
Pretty cool! How does it work when someone is not logged into github?
I'm cc'ing my colleagues @Kongkille and @FelixDQ who will be able to follow up.

**Comment by GitMatze** [comment]
Not sure what you mean... This is how I thought this could work: 
You create a github user named website-contributions. Using a token of this account you can make it automatically post messages, either by opening a new issue for every contribution or by commenting on a generic issue created for this purpose. 
This cannot be implemented in the frontend, however, because the secret token would be exposed. So I thought you send the user input to the backend, store the contact data for potential further enquiries and post the message on github using the API.

**Comment by corradio** [comment]
That answers my question - makes sense.
I'm leaving on vacation but I'll let @Kongkille and @FelixDQ take over the discussion and assess whether or not this is something that can be introduced in the product.
In any case, thanks for taking the time pushing this!

**Comment by Kongkille** [comment]
I've done something similar in the past. It uses the Github API to open issues. These issues would then have the description text that the user has posted on the form.

I think it's a cool implementation, however, there are some things that may worry me when issues can be created so fast.

1. Higher chance of duplicate issues. 
2. Easier issue-creation may also lead to lower-quality issues.
3. Reduced engagement. We **want** people to join the Github and follow their issues through, hopefully staying on and contributing to other parts of the map.
4. Is there a cap on the number of issues there can be in a repository?

Right now, we already have such a high amount of issues, and some of them dating back quite a bit. I like the idea of making issue-creation easier for users who are not familiar with Github, but I am afraid that this might lead to an overflow of low-quality issues causing us to overlook more important issues that people have spent a great amount of time on.

**Comment by GitMatze** [comment]
Yep, cluttering the page with auto-generated issues is probably not a good idea. That's why I thought to create a generic issue that collects all website contributions. You could simply browse through them every once in a while and check if there's anything of value. 
I'm not sure what all this would yield but I feel like it could potentially open up quite a useful input stream. There sure  are a lot of people out there that would quickly drop a link but wouldn't take the hurdle to engage on github, be it due to lacking time, english skills, motivation or just because they have no idea what github is.
Anyway, I totally see your points and it might also be quite some work to implement this...

**Comment by Kongkille** [comment]
I absolutely agree with your point that getting input from those people who may not be comfortable with Github would be a great source of input. We just have to find a way in which it does not affect the input stream of those who can and want to contribute directly.

I am going to close this for now, but can I tag you if I open up an issue related to this in the future?

**Comment by GitMatze** [comment]
Sure!

**Pull request closed without merging**
