### PR TITLE
Added parser for IN-KL

### PR DESCRIPTION
**Pull request by vigeesh**
Added parser for Kerala, India. The data is parsed from sldckerala.com

### CODE REVIEW

**Comment by alixunderplatz** [comment]
@vigeesh Looks very promising, good job! One question: can you post a link to the data page from where you get the data? thanks!

**Comment by vigeesh** [comment]
http://sldckerala.com/index.php?id=1

**Comment by alixunderplatz** [comment]
@vigeesh thanks! is it hourly generation data or a daily sum? we need at least hourly data to display production and emissions on the map. unfortunately, processing cumulative daipy data is not possible at the moment.

**Comment by vigeesh** [comment]
Yes, it is a daily sum. I couldn't find a source for the hourly data.

**Comment by corradio** [comment]
Hi @vigeesh ,

Thank you for your contribution. Unfortunately we can only display hourly data at the moment. I will close this issue but please keep your code and let us know if hourly data pops up - it would be amazing to be able to add it ;-)

Olivier

**Pull request closed without merging**
