### PR TITLE
Auto-generated translations for missing strings

### PR DESCRIPTION
**Pull request by jld3103**
The translations are made using deepl. I checked most of the translations and they are all very very good.  
The script merges the English translation and the other translation and the translates all strings which were not translated before in the other language.

### CODE REVIEW

**Comment by Raffox97** [comment]
Italian translations are pratically all out of context, please exclude them from the commits.

**Comment by jld3103** [comment]
The German translations were good, so I thought the others would be good too.

**Comment by alixunderplatz** [comment]
Hi @jld3103 
The zone/country translations in this commit are partially very, very weird and wrong for the German translation as well. 
I think having something translated by a machine is no option for files with a structure like ours, where many words are out of context. This needs to be done by humans, even if it is really annoying and time consuming, else it will lead to a wrong translation.

**Comment by brunolajoie** [comment]
Many thanks for the try @jld3103!

**Pull request closed without merging**
