### PR TITLE
Drag and drop states (debug tool)

### PR DESCRIPTION
**Pull request by pierresegonne**
## What

Add a sneaky drag and drop zone on emap front-end where a state can be dropped to display the emap based on any state from the gcloud storage

### CODE REVIEW

**Comment by fbarl** [comment]
Wow that seems like a very handy debugging feature @pierresegonne!

I'm probably the last one who's made major changes to the frontend code so please let me know if you need any help proceeding :wink:

**Comment by pierresegonne** [comment]
Hey @fbarl 

Yes you could definitely take over on this one, I left it in the open because we didn't define exactly how to integrate it properly (I am not sure we want it on prod) and because the priority on this is very low.

**Comment by corradio** [comment]
cc @FelixDQ

**Comment by FelixDQ** [comment]
I'll take over this one, and then we'll consider how to integrate it properly.

**Comment by Kongkille** [comment]
@FelixDQ given the time this has been up, I think we should probably close it. We can perhaps still look to do it in the future, but I'm not sure exactly how it should be implemented, so it might be easier to just close it.

**Comment by FelixDQ** [comment]
yea okay. It's a pretty neat debug feature, but we will probably not use it anytime soon. So closing it, for now, makes sense

**Pull request closed without merging**
