### PR TITLE
Update Belgian Capacities

### PR DESCRIPTION
**Pull request by Fred-3000**
Gas, Nuclear from ENTSO-E
Wind from Elia (https://www.elia.be/en/grid-data/power-generation/wind-power-generation)

First time doing this, so forgive any possible mistakes :)

### CODE REVIEW

**Review by FelixDQ — COMMENTED** [review]
Thank you! Can you also update the source in DATA_SOURCES.md? 

https://github.com/tmrowco/electricitymap-contrib/blob/master/DATA_SOURCES.md

**Comment by Fred-3000** [comment]
I've managed to do it in a separate pull request. Github is a bit overwhelming as a newbie...

**Comment by veqtrus** [comment]
> I've managed to do it in a separate pull request. GitHub is a bit overwhelming as a newbie...

I think it's because you didn't create a new branch for this change and tried to edit it directly so GitHub created an 'invisible' branch. In the other PR there seems to be a proper branch.

**Comment by Kongkille** [comment]
Moved to https://github.com/tmrowco/electricitymap-contrib/pull/2738

**Pull request closed without merging**
