### PR TITLE
update zone.json "de"

### PR DESCRIPTION
**Pull request by Bohne13**
updated netto installed capacity from Frauenhofer ISE (data from 27. DEC 2018)

### CODE REVIEW

**Comment by jarek** [comment]
Just to double-check... where do figures for geothermal and hydro storage actually come from? https://www.energy-charts.de/power_inst.htm?year=2018&period=annual&type=power_inst is given as source in readme and has the values as in the PR, but I don't see geothermal and hydro there.

**Comment by Bohne13** [comment]
@jarek Form geothermal data, I found a study or a website with data from 2018. I try to find it again!
For hydro storage, truly I haven't found current data from 2018.
With more time for searching the web, probably I could find some data.

**Comment by corradio** [comment]
@brunolajoie I think you can merge

**Comment by alixunderplatz** [comment]
@jarek I think we took hydro storage from the BNetzA Kraftwerksliste back then

**Pull request merged**
