### PR TITLE
Introducing swissgrid TSO parser (#1015)

### PR DESCRIPTION
**Pull request by ajoga**
This follow the objectives described in #1015. 

I'm not sure what else to do, should I edit the exchanges.json too? (ping @alixunderplatz )

### CODE REVIEW

**Comment by martincollignon** [comment]
thanks a ton @ajoga ! @alixunderplatz are we good to go?

**Comment by corradio** [comment]
Hi @ajoga and @alixunderplatz 
Have you looked at the data differences between ENTSOE and SwissGrid?
How comprehensive is the data?

**Comment by martincollignon** [comment]
Hi @ajoga and @alixunderplatz , a friendly bump so we can merge it!

**Comment by ajoga** [comment]
Hi @martincollignon thanks for the nudge. @corradio I'm not sure what / how to look at the parsers in order to properly answer your question. What would you like me to look for?

**Comment by corradio** [comment]
> Hi @martincollignon thanks for the nudge. @corradio I'm not sure what / how to look at the parsers in order to properly answer your question. What would you like me to look for?

Hello,

I think comparing the energy mix for a few times would be a good start. We know ENTSOE has some issues so we'd like to compare it with SwissGrid to see if the coverage is better.

Olivier

**Comment by q--** [comment]
@corradio FYI this parser only fetches exchange data from Swissgrid, not generation mix

**Comment by tth4vb** [comment]
Quick update here - we've been in talks with the Swiss energy ministry who have proposed a good solution to getting more complete CH data that they'll be posting about on GH soon, so I'm going to close this PR for now.

**Pull request closed without merging**
