### PR TITLE
Update Nepal Capacity in zones.json

### PR DESCRIPTION
**Pull request by Subarna578**

### CODE REVIEW

**Comment by Subarna578** [comment]
Please review the concerned file and merge it.

**Comment by corradio** [comment]
Can you add the source of those capacity numbers in the README?

**Comment by Subarna578** [comment]
Yes, I will add that. Thanks.

**Comment by martincollignon** [comment]
As an exception I'll merge both. In the future it'd be great if you could work in one branch. Thanks for your help!

**Pull request merged**
