### PR TITLE
Adding fetch_production function for Czech 15 minutely data

### PR DESCRIPTION
**Pull request by gecoffman**
There are other data sets provided via the API but wanted to start with the generation/production data set first.

First time contributing to the project, so apologies in advance for any glaring issues/mistakes.

### CODE REVIEW

**Comment by corradio** [comment]
Hi @gecoffman ,

Thank you very much for this PR. We have several algorithms internally that are highly sensitive on the data quality of countries on the EU system, and thus changing a data source requires a bit more work to make sure there's no regression.
First of, are you able to check the output of this new parser and compare it with the old ENTSOE parser to see how well they align?
You might be able to use this:
https://github.com/tmrowco/electricitymap-contrib#testing-a-parser

After we validate real-time data we will have to check historical data.

**Comment by systemcatch** [comment]
Error on circleci, this looks similar to what we fixed in #1980 
```shell
+ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
0
+ pylint -E parsers/AM.py parsers/AR.py parsers/AU.py parsers/AU_WA.py parsers/AW.py parsers/AX.py parsers/BD.py parsers/BG.py parsers/BO.py parsers/BR.py parsers/CA_AB.py parsers/CA_BC.py parsers/CA_NB.py parsers/CA_NS.py parsers/CA_ON.py parsers/CA_PE.py parsers/CA_YT.py parsers/CL.py parsers/CR.py parsers/CY.py parsers/CZ.py parsers/DK_BHM.py parsers/DK.py parsers/DO.py parsers/EIA.py parsers/ELEXON.py parsers/ENTE.py parsers/ENTSOE.py parsers/ES_CN.py parsers/ES_IB.py parsers/ESIOS.py parsers/example.py parsers/FO.py parsers/FR.py parsers/GB_NIR.py parsers/GB_ORK.py parsers/GE.py parsers/GT.py parsers/HOPS.py parsers/IN_AP.py parsers/IN_CT.py parsers/IN_DL.py parsers/IN_GJ.py parsers/__init__.py parsers/IN_KA.py parsers/IN_PB.py parsers/IN.py parsers/IN_UP.py parsers/IN_UT.py parsers/IQ.py parsers/JP-KY.py parsers/JP.py parsers/KR.py parsers/MD.py parsers/MX.py parsers/MY_WM.py parsers/NA.py parsers/NI.py parsers/NL.py parsers/NZ.py parsers/occtonet.py parsers/PA.py parsers/PE.py parsers/RE.py parsers/RU.py parsers/SE.py parsers/SG.py parsers/statnett.py parsers/SV.py parsers/TR.py parsers/TW.py parsers/UA.py parsers/US_BPA.py parsers/US_CA.py parsers/US_HI.py parsers/US_IPC.py parsers/US_MISO.py parsers/US_NEISO.py parsers/US_NY.py parsers/US_PJM.py parsers/US_SEC.py parsers/US_SPP.py parsers/US_TX.py parsers/UY.py -d unsubscriptable-object,unsupported-assignment-operation
************* Module electricitymap.parsers.AX
parsers/AX.py:168:4: E0633: Attempting to unpack a non-sequence defined at line 5 of  (unpacking-non-sequence)
Exited with code 2
```

**Comment by robertahunt** [comment]
@corradio Can this be closed now? Or are there more checks we need to do?

**Comment by corradio** [comment]
@robertahunt I'm a bit wary to change datasource for CZ as this might impact our marginal algorithm if the data quality is not perfect.
Ideally, we should test this parser by fetching historical data and comparing it with the existing data to make sure we have the same quality.
This will require some work and we might even need to set up a better process internally.
Due to the doubt it poses I wanted to postpone this a bit more until we have time to investigate how deal with those requests appropriately.

**Comment by corradio** [comment]
@gecoffman or @robertahunt has one of you time to compare ENTSOE output with this new parser's output to check if we can merge this?

**Comment by corradio** [comment]
@gecoffman are you able to do the checks and changes?

**Comment by robertahunt** [comment]
I gave this a quick look. The numbers reported on their site https://www.ceps.cz/en/all-data#Generation seem quite comparable to ENTSOE's numbers - not exactly the same, but within 10%. 

A couple of areas of uncertainty though:
- right now the parser does not work for, the response I get from the server is a 500 error, but it does not make the code fail - the code instead just returns 0s, I am adding a suggestion for this
- TPP is mapped to 'geothermal', but I think this should be 'coal'
- ApPP is reported by the czech authority, but is not captured here - autoproducers, that should probably go into unknown
- the authority does not specify a biomass category, but the numbers from ENTSOE are close to those for AltPP - alternative power plant, I think someone should check if this is biomass or if biomass is included in TPP (thermal)

**Comment by FelixDQ** [comment]
Hi all, sorry for the inactivity on this.

It seems like there is currently a bit of work left for this to be completed:
- [ ] Returns datetime as a string which currently makes parser crash.
- [ ] Currently only reports 0 for all productions. Doesn't seem like it actually fetches any data.
- [ ] Data investigations pointed out by Roberta above.

Let me know if someone wants to pick this up (@gecoffman? Or someone else?). Otherwise, I think that we have to close this for now, unfortunately.

**Comment by FelixDQ** [comment]
Closing this for now. Please open a new issue if someone wants to pick this up again.

**Pull request closed without merging**
